#ifndef GAME_RESOURCE_H
#define GAME_RESOURCE_H

/**
 * @file
 * Type definitions for resources
 */

/**
 * Resource types
 */

const static int RESOURCE_MAX[2] = {
        16,
        36,
};
const static int RESOURCE_MAX_FOOD[2] = {
        7,
        9,
};

enum {
    RESOURCE_NONE = 0,
    RESOURCE_WHEAT = 1, RESOURCE_GRAIN = 1,
    RESOURCE_VEGETABLES = 2, RESOURCE_MEAT_PH = 2,
    RESOURCE_FRUIT = 3, RESOURCE_LETTUCE = 3,
    RESOURCE_OLIVES = 4, RESOURCE_CHICKPEAS = 4,
    RESOURCE_VINES = 5, RESOURCE_POMEGRANATES = 5,
    RESOURCE_MEAT_C3 = 6, RESOURCE_FIGS = 6,
    RESOURCE_WINE = 7, RESOURCE_FISH = 7,
    RESOURCE_OIL_C3 = 8, RESOURCE_GAMEMEAT = 8,
    RESOURCE_IRON = 9, RESOURCE_STRAW = 9,
    RESOURCE_TIMBER_C3 = 10, RESOURCE_WEAPONS_PH = 10,
    RESOURCE_CLAY_C3 = 11, RESOURCE_CLAY_PH = 11,
    RESOURCE_MARBLE_C3 = 12, RESOURCE_BRICKS = 12,
    RESOURCE_WEAPONS_C3 = 13, RESOURCE_POTTERY_PH = 13,
    RESOURCE_FURNITURE = 14, RESOURCE_BARLEY = 14,
    RESOURCE_POTTERY_C3 = 15, RESOURCE_BEER = 15,
    RESOURCE_DENARII = 16, RESOURCE_FLAX = 16,
    RESOURCE_TROOPS = 17, RESOURCE_LINEN = 17,
    RESOURCE_GEMS = 18,
    RESOURCE_LUXURY_GOODS = 19,
    RESOURCE_TIMBER_PH = 20,
    RESOURCE_GOLD = 21,
    RESOURCE_REEDS = 22,
    RESOURCE_PAPYRUS = 23,
    RESOURCE_STONE = 24,
    RESOURCE_LIMESTONE = 25,
    RESOURCE_GRANITE = 26,
    RESOURCE_UNUSED12 = 27,
    RESOURCE_CHARIOTS = 28,
    RESOURCE_COPPER = 29,
    RESOURCE_SANDSTONE = 30,
    RESOURCE_OIL_PH = 31,
    RESOURCE_HENNA = 32,
    RESOURCE_PAINT = 33,
    RESOURCE_LAMPS = 34,
    RESOURCE_MARBLE_PH = 35,
    RESOURCE_UNUSED16 = 36,
    // helper constants
    RESOURCE_MIN = 1,
//    RESOURCE_MAX[GAME_ENV] = 16,
    RESOURCE_MIN_FOOD = 1,
//    RESOURCE_MAX_FOOD[GAME_ENV] = 7
};

enum {
//    INVENTORY_FOOD1 = 0,
//    INVENTORY_FOOD2 = 1,
//    INVENTORY_FOOD3 = 2,
//    INVENTORY_FOOD4 = 3,
    INVENTORY_GOOD1 = 5,
    INVENTORY_GOOD2 = 7,
    INVENTORY_GOOD3 = 6,
    INVENTORY_GOOD4 = 4,
    // helper constants
    INVENTORY_MIN_FOOD = 0,
    INVENTORY_MAX_FOOD = 4,
    INVENTORY_MIN_GOOD = 4,
    INVENTORY_MAX_GOOD = 8,
    INVENTORY_MAX = 8
};

int ALLOWED_FOODS(int i);
bool is_food_allowed(int resource);

const int INV_RESOURCES[2][20] = {
    {
        RESOURCE_POTTERY_C3,
        RESOURCE_FURNITURE,
        RESOURCE_OIL_C3,
        RESOURCE_WINE,
        RESOURCE_WHEAT,
        RESOURCE_VEGETABLES,
        RESOURCE_FRUIT,
        RESOURCE_MEAT_C3,
    },
    {
        RESOURCE_POTTERY_PH,
        RESOURCE_LUXURY_GOODS,
        RESOURCE_LINEN,
        RESOURCE_BEER,
        RESOURCE_GRAIN,
        RESOURCE_MEAT_PH,
        RESOURCE_LETTUCE,
        RESOURCE_CHICKPEAS,
        RESOURCE_POMEGRANATES,
        RESOURCE_FIGS,
        RESOURCE_FISH,
        RESOURCE_GAMEMEAT,
    }
};

enum {
    WORKSHOP_NONE = 0,
    WORKSHOP_OLIVES_TO_OIL = 1,
    WORKSHOP_VINES_TO_WINE = 2,
    WORKSHOP_IRON_TO_WEAPONS = 3,
    WORKSHOP_TIMBER_TO_FURNITURE = 4,
    WORKSHOP_CLAY_TO_POTTERY = 5
};

enum {
    RESOURCE_IMAGE_STORAGE = 0,
    RESOURCE_IMAGE_CART = 1,
    RESOURCE_IMAGE_FOOD_CART = 2,
    RESOURCE_IMAGE_ICON = 3
};

int resource_image_offset(int resource, int type);

int resource_is_food(int resource);

int resource_to_workshop_type(int resource);

#endif // GAME_RESOURCE_H
