var building_menu = [
	{
		id: BUILD_MENU_VACANT_HOUSE,
		anim: { pack:PACK_GENERAL, id:117, offset:1 },
		items: [BUILDING_HOUSE_VACANT_LOT]
  },

  {
  	id: BUILD_MENU_CLEAR_LAND,
  	anim: { pack:PACK_GENERAL, id:117, offset:9 },
  	items: [BUILDING_CLEAR_LAND]
  },

  {
  	id: BUILD_MENU_ROAD,
  	anim: { pack:PACK_GENERAL, id:117, offset:5 },
  	items: [BUILDING_ROAD]
  },

  {
  	id: BUILD_MENU_WATER_CROSSINGS,
  	anim: { pack:PACK_GENERAL, id:117, offset:8 },
  	items: [BUILDING_LOW_BRIDGE, BUILDING_FERRY]
  },

  {
  	id: BUILD_MENU_HEALTH,
  	anim: { pack:PACK_GENERAL, id:117, offset:4 },
  	items: [BUILDING_WELL, BUILDING_WATER_SUPPLY, BUILDING_DENTIST, BUILDING_APOTHECARY, BUILDING_PHYSICIAN, BUILDING_MORTUARY]
  },

  {
  	id: BUILD_MENU_RELIGION,
  	anim: { pack:PACK_GENERAL, id:117, offset:7 },
  	items: [BUILDING_MENU_SHRINES, BUILDING_MENU_TEMPLES, BUILDING_MENU_TEMPLE_COMPLEX, BUILDING_MENU_MONUMENTS, BUILDING_FESTIVAL_SQUARE]
  },

  {
  	id: BUILD_MENU_EDUCATION,
  	anim: { pack:PACK_GENERAL, id:117, offset:11 },
  	items: [BUILDING_SCRIBAL_SCHOOL, BUILDING_LIBRARY]
  },

  {
  	id: BUILD_MENU_ENTERTAINMENT,
  	anim: { pack:PACK_GENERAL, id:117, offset:3 },
  	items: [BUILDING_BOOTH, BUILDING_BANDSTAND, BUILDING_PAVILLION, BUILDING_SENET_HOUSE,
  					BUILDING_JUGGLER_SCHOOL, BUILDING_CONSERVATORY, BUILDING_DANCE_SCHOOL]
  },

  {
  	id: BUILD_MENU_ADMINISTRATION,
  	anim: { pack:PACK_GENERAL, id:117, offset:8 },
  	items: [BUILDING_FIREHOUSE, BUILDING_ARCHITECT_POST, BUILDING_POLICE_STATION, BUILDING_TAX_COLLECTOR,
     				BUILDING_COURTHOUSE, BUILDING_VILLAGE_PALACE, BUILDING_TOWN_PALACE, BUILDING_CITY_PALACE,
     				BUILDING_PERSONAL_MANSION, BUILDING_FAMILY_MANSION, BUILDING_DYNASTY_MANSION, BUILDING_ROADBLOCK, 
     				BUILDING_MENU_WATER_CROSSINGS, BUILDING_MENU_BEAUTIFICATION]
  },

  {
  	id: BUILD_MENU_BEAUTIFICATION,
  	anim: { pack:PACK_GENERAL, id:117, offset:8 },
  	items: [BUILDING_GARDENS, BUILDING_PLAZA, BUILDING_SMALL_STATUE, BUILDING_MEDIUM_STATUE, BUILDING_LARGE_STATUE]
  },

  {
  	id: BUILD_MENU_SECURITY,
  	anim: { pack:PACK_GENERAL, id:117, offset:12 },
  	items: [BUILDING_MENU_DEFENSES, BUILDING_RECRUITER,BUILDING_MENU_FORTS,
     				BUILDING_MILITARY_ACADEMY, BUILDING_WEAPONSMITH, BUILDING_CHARIOTS_WORKSHOP,
     				BUILDING_WARSHIP_WHARF, BUILDING_TRANSPORT_WHARF]
  },

	{
  	id: BUILD_MENU_INDUSTRY,
  	anim: { pack:PACK_GENERAL, id:117, offset:6 },
  	items: [BUILDING_MENU_RAW_MATERIALS, BUILDING_JEWELS_WORKSHOP, BUILDING_POTTERY_WORKSHOP,
     				BUILDING_BREWERY_WORKSHOP, BUILDING_WEAVER_WORKSHOP, BUILDING_PAPYRUS_WORKSHOP,
     				BUILDING_BRICKS_WORKSHOP, BUILDING_LAMP_WORKSHOP, BUILDING_PAINT_WORKSHOP,
     				BUILDING_SHIPWRIGHT, BUILDING_MENU_CONSTURCTION_GUILDS]
  },

  {
  	id: BUILD_MENU_FARMS,
  	anim: { pack:PACK_GENERAL, id:117, offset:10 },
  	items: [BUILDING_GRAIN_FARM, BUILDING_LETTUCE_FARM, BUILDING_POMEGRANATES_FARM,
     				BUILDING_CHICKPEAS_FARM, BUILDING_FIGS_FARM, BUILDING_BARLEY_FARM, BUILDING_FLAX_FARM,
     				BUILDING_HENNA_FARM]
  },

  {
  	id: BUILD_MENU_RAW_MATERIALS,
  	anim: { pack:PACK_GENERAL, id:117, offset:6 },
  	items: [BUILDING_CLAY_PIT, BUILDING_GEMSTONE_MINE, BUILDING_GOLD_MINE,
     				BUILDING_COPPER_MINE, BUILDING_STONE_QUARRY, BUILDING_LIMESTONE_QUARRY,
     				BUILDING_GRANITE_QUARRY, BUILDING_SANDSTONE_QUARRY, BUILDING_REED_GATHERER,
     				BUILDING_WOOD_CUTTERS]
  },

  {
  	id: BUILD_MENU_GUILDS,
  	anim: { pack:PACK_GENERAL, id:117, offset:6 },
  	items: [BUILDING_CARPENTERS_GUILD, BUILDING_BRICKLAYERS_GUILD, BUILDING_STONEMASONS_GUILD, BUILDING_ARTISANS_GUILD]
  },

  {
  	id: BUILD_MENU_TEMPLES,
  	anim: { pack:PACK_GENERAL, id:117, offset:7 },
		items: [BUILDING_TEMPLE_OSIRIS, BUILDING_TEMPLE_RA, BUILDING_TEMPLE_PTAH, BUILDING_TEMPLE_SETH, BUILDING_TEMPLE_BAST]
  },

  {
  	id: BUILD_MENU_LARGE_TEMPLES,
  	anim: { pack:PACK_GENERAL, id:117, offset:7 },
  	items: []
  },

	{
  	id: BUILD_MENU_TEMPLE_COMPLEX,
  	anim: { pack:PACK_GENERAL, id:117, offset:7 },
  	items: [BUILDING_TEMPLE_COMPLEX_OSIRIS, BUILDING_TEMPLE_COMPLEX_RA, BUILDING_TEMPLE_COMPLEX_PTAH,
     				BUILDING_TEMPLE_COMPLEX_SETH, BUILDING_TEMPLE_COMPLEX_BAST, BUILDING_TEMPLE_COMPLEX_ALTAR,
     				BUILDING_TEMPLE_COMPLEX_ORACLE]
  },

  {
    id: BUILD_MENU_LARGE_TEMPLES,
  	items: []
  },

  {
  	it: BUILD_MENU_FORTS,
  	anim: { pack:PACK_GENERAL, id:117, offset:12 },
  	items: [BUILDING_FORT_INFANTRY, BUILDING_FORT_ARCHERS, BUILDING_FORT_CHARIOTEERS]
  },

  {
  	it: BUILD_MENU_FOOD,
  	anim: { pack:PACK_GENERAL, id:117, offset:10 },
  	items: [BUILDING_MENU_FARMS, BUILDING_WATER_LIFT, BUILDING_IRRIGATION_DITCH, BUILDING_FISHING_WHARF,
     				BUILDING_CATTLE_RANCH, BUILDING_HUNTING_LODGE, BUILDING_WORK_CAMP]
  },

  {
  	id: BUILD_MENU_DISTRIBUTION,
  	anim: { pack:PACK_GENERAL, id:117, offset:2 },
  	items: [BUILDING_GRANARY, BUILDING_BAZAAR, BUILDING_STORAGE_YARD, BUILDING_DOCK]
  },

  {
  	id: BUILD_MENU_SHRINES,
  	anim: { pack:PACK_GENERAL, id:117, offset:7 },
  	items: [BUILDING_SHRINE_OSIRIS, BUILDING_SHRINE_RA, BUILDING_SHRINE_PTAH, BUILDING_SHRINE_SETH, BUILDING_SHRINE_BAST]
  },

  {
  	id: BUILD_MENU_MONUMENTS,
  	anim: { pack:PACK_GENERAL, id:117, offset:7 },
  	items: [BUILDING_SMALL_MASTABA, BUILDING_SMALL_ROYAL_TOMB, BUILDING_MEDIUM_ROYAL_TOMB,
     				BUILDING_LARGE_ROYAL_TOMB, BUILDING_GRAND_ROYAL_TOMB, BUILDING_PYRAMID,
     				BUILDING_SPHINX, BUILDING_MAUSOLEUM, BUILDING_ALEXANDRIA_LIBRARY, BUILDING_CAESAREUM,
     				BUILDING_PHAROS_LIGHTHOUSE, BUILDING_ABU_SIMBEL]
  },

  {
  	id: BUILD_MENU_DEFENCES,
  	anim: { pack:PACK_GENERAL, id:117, offset:12 },
  	items: [BUILDING_MUD_WALL, BUILDING_MUD_TOWER, BUILDING_MUD_GATEHOUSE,
     				BUILDING_BRICK_WALL, BUILDING_BRICK_TOWER, BUILDING_BRICK_GATEHOUSE]
  }
]
