log_info("Ozymandias: building sounds started")

building_sounds = [
  { type: "tax_collector", 						sound: "wavs/taxfarm.wav"},
  { type: "palace", 									sound: "wavs/palace.wav"},
  { type: "garden",										sound: "wavs/park1.wav"},
  { type: "plaza", 										sound: "wavs/FANFARE1.wav"},
  { type: "statue", 									sound: "wavs/statue1.wav"},
  { type: "barley_farm", 							sound: "wavs/barleyfarm.wav"},
  { type: "flax_farm", 								sound: "wavs/flaxfarm.wav"},
  { type: "grain_farm",								sound: "wavs/farm1.wav"},
  { type: "lettuce_farm",							sound: "wavs/lettucefarm.wav"},
  { type: "pomegranades_farm",				sound: "wavs/pomfarm.wav"},
	{ type: "chickpeas_farm",						sound: "wavs/chickfarm.wav"},
	{ type: "figs_farm",								sound: "wavs/figs_farm.wav"},
	{ type: "henna_farm",								sound: "wavs/farm2.wav"},
	{ type: "hunting_lodge", 						sound: "wavs/lo_hunt.wav" },
	{ type: "marble_quarry", 						sound: "wavs/marble.wav" },
	{ type: "iron_mine", 								sound: "wavs/gold.wav" },
	{ type: "gold_mine", 								sound: "wavs/gold.wav" },
	{ type: "timber_yard", 							sound: "wavs/lumber.wav" },
	{ type: "clay_pit", 								sound: "wavs/clay.wav" },
	{ type: "reed_farm", 								sound: "wavs/reedfarm.wav" },
	{ type: "brewery",									sound: "wavs/brewery.wav"},
	{ type: "flax_workshop",						sound: "wavs/flaxfarm.wav"},
	{ type: "weapons_workshop",				  sound: "wavs/weapon.wav"},
	{ type: "luxury_workshop",				  sound: "wavs/gem_r.wav"},
	{ type: "pottery_workshop",				  sound: "wavs/pottery.wav"},
	{ type: "brick_maker",				 			sound: "wavs/brick.wav"},
	{ type: "work_camp",				 		  	sound: "wavs/eng_r.wav"},
	{ type: "wharf",				 		  			sound: "wavs/shipyrd_r.wav"},
]
