log_info("akhenaten: building sounds started")

building_sounds = [
  { type: "tax_collector", 						sound: "Wavs/taxfarm.wav"},
  { type: "palace", 									sound: "Wavs/palace.wav"},
  { type: "garden",										sound: "Wavs/park1.wav"},
  { type: "plaza", 										sound: "Wavs/FANFARE1.wav"},
  { type: "statue", 									sound: "Wavs/statue1.wav"},
  { type: "barley_farm", 							sound: "Wavs/barleyfarm.wav"},
  { type: "flax_farm", 								sound: "Wavs/flaxfarm.wav"},
  { type: "grain_farm",								sound: "Wavs/farm1.wav"},
  { type: "lettuce_farm",							sound: "Wavs/lettucefarm.wav"},
  { type: "pomegranades_farm",				sound: "Wavs/pomfarm.wav"},
	{ type: "chickpeas_farm",						sound: "Wavs/chickfarm.wav"},
	{ type: "figs_farm",								sound: "Wavs/figs_farm.wav"},
	{ type: "henna_farm",								sound: "Wavs/farm2.wav"},
	{ type: "hunting_lodge", 						sound: "Wavs/lo_hunt.wav" },
	{ type: "marble_quarry", 						sound: "Wavs/marble.wav" },
	{ type: "iron_mine", 								sound: "Wavs/gold.wav" },
	{ type: "gold_mine", 								sound: "Wavs/gold.wav" },
	{ type: "timber_yard", 							sound: "Wavs/lumber.wav" },
	{ type: "clay_pit", 								sound: "Wavs/clay.wav" },
	{ type: "reed_farm", 								sound: "Wavs/reedfarm.wav" },
	{ type: "brewery",									sound: "Wavs/brewery.wav"},
	{ type: "flax_workshop",						sound: "Wavs/flaxfarm.wav"},
	{ type: "weapons_workshop",				  sound: "Wavs/weapon.wav"},
	{ type: "luxury_workshop",				  sound: "Wavs/gem_r.wav"},
	{ type: "pottery_workshop",				  sound: "Wavs/pottery.wav"},
	{ type: "brick_maker",				 			sound: "Wavs/brick.wav"},
	{ type: "work_camp",				 		  	sound: "Wavs/eng_r.wav"},
	{ type: "wharf",				 		  			sound: "Wavs/shipyrd_r.wav"},
	{ type: "shipyard",				 		  		sound: "Wavs/shipyrd.wav"},
	{ type: "engineer_post", 						sound: "Wavs/eng.wav"},
	{ type: "shrine_osiris", 						sound: "Wavs/shr_osiris.wav"},
	{ type: "shrine_ra", 								sound: "Wavs/SHR_RA.wav"},
	{ type: "shrine_ptah", 							sound: "Wavs/SHR_PTAH.wav"},
	{ type: "shrine_seth", 							sound: "Wavs/SHR_SETH.wav"},
	{ type: "shrine_bast", 							sound: "Wavs/SHR_BAST.wav"},
	{ type: "temple_osiris", 						sound: "Wavs/tem_osiris_l.wav"},
	{ type: "temple_ra", 								sound: "Wavs/tem_RA_l.wav"},
	{ type: "temple_ptah", 							sound: "Wavs/tem_PTAH_l.wav"},
	{ type: "temple_seth", 							sound: "Wavs/tem_SETH_l.wav"},
	{ type: "temple_bast", 							sound: "Wavs/tem_BAST_l.wav"},
	{ type: "booth", 										sound: "Wavs/jugger_r.wav"},
	{ type: "bandstand", 								sound: "Wavs/music_r.wav"},
	{ type: "juggler_school",						sound: "Wavs/juggler_school.wav"},
	{ type: "conservatory", 						sound: "Wavs/music_school.wav"},
	{ type: "dance_school", 						sound: "Wavs/dance_school.wav"},
	{ type: "bullfight_school", 				sound: "Wavs/bullfight_school.wav"},
	{ type: "apothecary", 							sound: "Wavs/apothecary.wav"},
	{ type: "dentist", 									sound: "Wavs/dentist.wav"},
	{ type: "mortuary", 								sound: "Wavs/mortuary.wav"},
	{ type: "physician", 								sound: "Wavs/physician.wav"},
	{ type: "school_scribe",						sound: "Wavs/school_scribe.wav"},
	{ type: "papyrus_workshop",				  sound: "Wavs/paper.wav"},
	{ type: "cattle_ranch",				 	 		sound: "Wavs/cowfarm_r.wav"},
]
