log_info("akhenaten: localization config started")

localization = [
  {key: "#popup_dialog_quit", group:5, id:0 },
  {key: "#popup_dialog_open_trade", group:5, id:2 },
  {key: "#popup_dialog_send_goods", group:5, id:7 },
  {key: "#popup_dialog_not_enough_goods", group:5, id:8 },
  {key: "#popup_dialog_no_legions_available", group:5, id:10 },
  {key: "#popup_dialog_no_legions_selected", group:5, id:12 },
  {key: "#popup_dialog_send_troops", group:5, id:14 },
  {key: "#popup_dialog_delete_fort", group:5, id:16 },
  {key: "#popup_dialog_delete_bridge", group:5, id:20 },
  {key: "#popup_dialog_quit_without_saving", group:5, id:22 },
  {key: "#exit_without_saving", group:5, id:23 },
  {key: "#popup_dialog_no_festival_square", group:5, id:88 },
  {key: "#popup_dialog_delete_dynasty", group:5, id:90 },
  {key: "#popup_dialog_no_dynasty", group:5, id:94 },
  {key: "#replay_mission", group:1, id:2 },
  {key: "#granary_info_title", group:98, id:0 },
  {key: "#granary_no_road_access", group:69, id:25 },
  {key: "#granary_kingdom_supplies_grain", group:98, id:4 },
  {key: "#granary_storing", group:98, id:2 },
  {key: "#granary_space_for", group:98, id:3 },
  {key: "#granary_units", group:8, id:17 },
  {key: "#chief_overseer", group:61, id:0 },
  {key: "#chief_adv_sentiment", group:61, id:1 },
  {key: "#chief_adv_migration", group:61, id:2 },
  {key: "#chief_adv_workers", group:61, id:3 },
  {key: "#chief_adv_foodstocks", group:61, id:4 },
  {key: "#chief_adv_foodconsumption", group:61, id:5 },
  {key: "#chief_adv_health", group:61, id:6 },
  {key: "#chief_adv_religion", group:61, id:7 },
  {key: "#chief_adv_finance", group:61, id:8 },
  {key: "#chief_adv_crime", group:61, id:9 },
  {key: "#chief_adv_military", group:61, id:10 },
  {key: "#chief_adv_kingdom", group:61, id:11 },
  {key: "#chief_adv_nilometr", group:61, id:12 },
  {key: "#trade_overseer", group:54, id:0 },
  {key: "#trade_overseer_hint", group:54, id:1 },
  {key: "#building_have_no_access", group:69, id:25 },
  {key: "#bazaar_info_title", group: 97, id:0},
  {key: "#well_info_title", group:109, id:0},
  {key: "#trade_overseer_prices", group:54, id:30},
  {key: "#trade_overseer_prices_hint", group:68, id:108},
  {key: "#trade_overseer_goto_empire", group:54, id:2},
  {key: "#trade_overseer_goto_empire_hint", group:68, id:42},
  {key: "#festival_square_info_title", group:188, id:0},
  {key: "#visit_rating_advisor", group:105, id:3},
  {key: "#gardens_describe", group:79, id:1},

  {key: "#hunter_ostrich_good_city", lang:"en", text: "I like it here, but there is always room for improvement."},
]
