log_info("akhenaten: load modules started")

include(":math.js")
include(":common.js")
include(":images.js")
include(":city_sounds.js")
include(":mission_sounds.js")
include(":walker_sounds.js")
include(":building_sounds.js")
include(":overlays.js")
include(":building_info.js")
include(":walker_images.js")
