log_info("akhenaten: overlays started")

overlays = [
  {
  	id:OVERLAY_RELIGION_OSIRIS,
  	caption:"Osiris",
  	walkers:[FIGURE_PRIEST],
  	buildings:[BUILDING_TEMPLE_OSIRIS, BUILDING_TEMPLE_COMPLEX_OSIRIS, BUILDING_SHRINE_OSIRIS],
  	tooltip_base:0,
  	tooltips:[]
  },

  {
  	id:OVERLAY_RELIGION_RA,
  	caption:"Ra",
  	walkers:[FIGURE_PRIEST],
  	buildings:[BUILDING_TEMPLE_RA, BUILDING_TEMPLE_COMPLEX_RA, BUILDING_SHRINE_RA],
  	tooltip_base:0,
  	tooltips:[]
  },

  {
    id:OVERLAY_RELIGION_SETH,
    walkers:[FIGURE_PRIEST],
    buildings:[BUILDING_TEMPLE_SETH, BUILDING_TEMPLE_COMPLEX_SETH, BUILDING_SHRINE_SETH],
  },

  {
    id:OVERLAY_RELIGION_PTAH,
    walkers:[FIGURE_PRIEST],
    buildings:[BUILDING_TEMPLE_PTAH, BUILDING_TEMPLE_COMPLEX_PTAH, BUILDING_SHRINE_PTAH],
  },

  {
    id:OVERLAY_RELIGION_BAST,
    walkers:[FIGURE_PRIEST],
    buildings:[BUILDING_TEMPLE_BAST, BUILDING_TEMPLE_COMPLEX_BAST, BUILDING_SHRINE_BAST],
  },

  {
    id:OVERLAY_WATER,
    walkers:[FIGURE_WATER_CARRIER],
    buildings:[BUILDING_WELL, BUILDING_MENU_BEAUTIFICATION, BUILDING_WATER_LIFT, BUILDING_WATER_SUPPLY],
  },

  {
    id:OVERLAY_APOTHECARY,
    walkers:[FIGURE_HERBALIST],
    buildings:[BUILDING_APOTHECARY],
  },

  {
    id:OVERLAY_RELIGION,
    walkers:[FIGURE_PRIEST],
    buildings:[ BUILDING_FESTIVAL_SQUARE,
                BUILDING_TEMPLE_RA, BUILDING_TEMPLE_COMPLEX_RA, BUILDING_SHRINE_RA,
                BUILDING_TEMPLE_OSIRIS, BUILDING_TEMPLE_COMPLEX_OSIRIS, BUILDING_SHRINE_OSIRIS, ],
  },

  {
    id:OVERLAY_BANDSTAND,
    walkers:[FIGURE_PRIEST],
    buildings:[BUILDING_CONSERVATORY, BUILDING_BANDSTAND],
  },

  {
    id:OVERLAY_BAZAAR_ACCESS,
    walkers:[FIGURE_MARKET_BUYER, FIGURE_MARKET_TRADER],
    buildings:[BUILDING_BAZAAR],
  },

  {
    id:OVERLAY_COUTHOUSE,
    walkers:[FIGURE_MAGISTRATE],
    buildings:[BUILDING_COURTHOUSE],
  },

  {
    id:OVERLAY_CRIME,
    walkers:[FIGURE_CONSTABLE, FIGURE_PROTESTER, FIGURE_CRIMINAL, FIGURE_TOMB_ROBER],
    buildings:[BUILDING_POLICE_STATION, BUILDING_FESTIVAL_SQUARE],
  },

  {
    id:OVERLAY_DAMAGE,
    walkers:[FIGURE_ARCHITECT],
    buildings:[BUILDING_ARCHITECT_POST, BUILDING_FESTIVAL_SQUARE],
  },

  {
    id:OVERLAY_DENTIST,
    walkers:[FIGURE_DENTIST],
    buildings:[BUILDING_DENTIST],
  },

  {
    id:OVERLAY_LIBRARY,
    walkers:[FIGURE_LIBRARIAN],
    buildings:[BUILDING_LIBRARY],
  },

  {
    id:OVERLAY_EDUCATION,
    walkers:[FIGURE_SCRIBER, FIGURE_LIBRARIAN, FIGURE_TEACHER],
    buildings:[BUILDING_SCRIBAL_SCHOOL, BUILDING_LIBRARY, BUILDING_ACADEMY],
  },

  {
    id:OVERLAY_ENTERTAINMENT,
    walkers:[FIGURE_JUGGLER, FIGURE_MUSICIAN, FIGURE_DANCER, FIGURE_SENET_PLAYER, FIGURE_CHARIOR_RACER],
    buildings:[ BUILDING_JUGGLER_SCHOOL, BUILDING_BOOTH, BUILDING_CONSERVATORY,
                BUILDING_BANDSTAND, BUILDING_DANCE_SCHOOL, BUILDING_PAVILLION,
                BUILDING_SENET_MASTER, BUILDING_SENET_HOUSE],
  },

  {
    id:OVERLAY_SENET_HOUSE,
    walkers:[FIGURE_CHARIOR_RACER],
    buildings:[BUILDING_SENET_MASTER, BUILDING_SENET_HOUSE],
  },

  {
    id:OVERLAY_FIRE,
    walkers:[FIGURE_FIREMAN],
    buildings:[BUILDING_FIREHOUSE, BUILDING_BURNING_RUIN, BUILDING_FESTIVAL_SQUARE],
  },

  {
    id:OVERLAY_HEALTH,
    walkers:[FIGURE_EMBALMER, FIGURE_HERBALIST, FIGURE_PHYSICIAN, FIGURE_DENTIST],
    buildings:[BUILDING_MORTUARY, BUILDING_APOTHECARY, BUILDING_PHYSICIAN, BUILDING_DENTIST],
  },

  {
    id:OVERLAY_BOOTH,
    walkers:[FIGURE_JUGGLER],
    buildings:[BUILDING_JUGGLER_SCHOOL, BUILDING_BOOTH],
  },

  {
    id:OVERLAY_MORTUARY,
    walkers:[FIGURE_EMBALMER],
    buildings:[BUILDING_MORTUARY],
  },

  {
    id:OVERLAY_FOOD_STOCKS,
    walkers:[FIGURE_EMBALMER],
    buildings:[BUILDING_BAZAAR, BUILDING_FISHING_WHARF, BUILDING_GRANARY],
  },

  {
    id:OVERLAY_PAVILION,
    walkers:[],
    buildings:[BUILDING_CONSERVATORY, BUILDING_DANCE_SCHOOL, BUILDING_PAVILLION],
  },

  {
    id:OVERLAY_PHYSICIAN,
    walkers:[FIGURE_PHYSICIAN],
    buildings:[BUILDING_PHYSICIAN],
  },

  {
    id:OVERLAY_SCRIBAL_SCHOOL,
    walkers:[FIGURE_TEACHER],
    buildings:[BUILDING_SCRIBAL_SCHOOL],
  },

  {
    id:OVERLAY_TAX_INCOME,
    walkers:[FIGURE_TAX_COLLECTOR],
    buildings:[BUILDING_TAX_COLLECTOR, BUILDING_TAX_COLLECTOR_UPGRADED, BUILDING_VILLAGE_PALACE, BUILDING_TOWN_PALACE, BUILDING_CITY_PALACE],
  },
]
