log_info("akhenaten: walker sounds started")

walker_sounds = [
 // artisan
 {type: "artisan_work_my_tools_need_for_monument", 			sound:"artisan_e01.wav"},
 {type: "artisan_work_i_write_history_of_egypt", 				sound:"artisan_e02.wav"},
 // barge
 {type: "barge_have_no_place_for_dock", 								sound:"barge_e01.wav"},
 {type: "barge_docked_wait_for_dockpushers", 						sound:"barge_e02.wav"},
 {type: "barge_city_not_trades", 												sound:"barge_e03.wav"},
 {type: "barge_i_like_to_trage", 												sound:"barge_e04.wav"},
 {type: "barge_amazing_trades", 												sound:"barge_e05.wav"},
 // caravan
 {type: "caravan_city_not_trades", 											sound:"caravan_e01.wav"},
 {type: "caravan_buy_for_less_sell_for_more", 					sound:"caravan_e02.wav"},
 {type: "caravan_its_my_life", 													sound:"caravan_e03.wav"},
 {type: "caravan_amazing_trades", 											sound:"caravan_e04.wav"},
 {type: "caravan_bad_trades", 													sound:"caravan_e05.wav"},
 // carpenter
 {type: "carpenter_work_my_tools_need_for_monument", 		sound:"carpenter_e01.wav"},
 {type: "carpenter_this_monument_will_be_short", 				sound:"carpenter_e02.wav"},
 // worker
 {type: "worker_going_to_workplace", 										sound:"worker_e02.wav"},
 {type: "worker_farm_is_flooded", 											sound:"worker_e03.wav"},
 {type: "worker_desease_can_start_at_any_moment", 			sound:"worker_g01.wav"},
 {type: "worker_no_food_in_city", 											sound:"worker_g02.wav"},
 {type: "worker_enemies_in_city", 											sound:"worker_g03.wav"},
 {type: "worker_need_workers", 													sound:"worker_g04.wav"},
 {type: "worker_gods_are_angry", 												sound:"worker_g05.wav"},
 {type: "worker_city_is_bad", 													sound:"worker_g06.wav"},
 {type: "worker_much_unemployments", 										sound:"worker_g07.wav"},
 {type: "worker_low_entertainment", 										sound:"worker_g08.wav"},
 {type: "worker_city_is_good", 													sound:"worker_g09.wav"},
 {type: "worker_city_is_amazing", 											sound:"worker_g10.wav"},
 // governor
 {type: "governor_city_left_much_nobles", 							sound:"governor_e01.WAV"},
 {type: "governor_festival_was_near", 									sound:"governor_e02.wav"},
 // hunter ostrich
 {type: "hunterostrich_hunting", 												sound:"hunt_ostrich_e01.wav"},
 {type: "hunterostrich_back", 													sound:"hunt_ostrich_e02.wav"},
 // library
 {type: "", sound: "library_g06.wav"},
 {type: "", sound: "library_g07.wav"},
 {type: "", sound: "library_g08.wav"},
 {type: "", sound: "library_g09.wav"},
 {type: "", sound: "library_g10.wav"},
 // magistrate
 {type: "magistrate_i_hope_we_are_ready", 							sound: "magistrate_e02.wav"},
 {type: "magistrate_no_criminals_in_city", 							sound: "magistrate_e03.wav"},
 {type: "magistrate_all_good_in_city", 									sound: "magistrate_e04.wav"},
 {type: "magistrate_streets_still_arent_safety", 				sound: "magistrate_e05.wav"},
 {type: "magistrate_disease_in_city", 									sound: "magistrate_g01.wav"},
 {type: "magistrate_no_food_in_city", 									sound: "magistrate_g02.wav"},
 {type: "magistrate_city_not_safety", 									sound: "magistrate_g03.wav"},
 {type: "magistrate_need_workers", 											sound: "magistrate_g04.wav"},
 {type: "magistrate_gods_are_angry", 										sound: "magistrate_g05.wav"},
 {type: "magistrate_city_bad_reputation", 							sound: "magistrate_g06.wav"},
 {type: "magistrate_much_unemployments", 								sound: "magistrate_g07.wav"},
 {type: "magistrate_no_entertainment_need", 						sound: "magistrate_g08.wav"},
 {type: "magistrate_city_not_bad", 											sound: "magistrate_g09.wav"},
 {type: "magistrate_city_is_amazing", 									sound: "magistrate_g10.wav"},
 // pharaoh
 {type: "", sound: "pharaoh_e01.wav"},
 // policeman
 {type: "policeman_low_crime_level", 										sound: "police_e01.WAV"},
 {type: "policeman_usual_crime_level", 									sound: "police_e02.WAV"},
 {type: "policeman_very_low_crime_level", 							sound: "police_e03.WAV"},
 {type: "policeman_iam_too_busy_that_talk", 						sound: "police_e04.WAV"},
 {type: "policeman_i_hope_my_work_is_need", 						sound: "police_e05.WAV"},
 {type: "policeman_city_not_safety", 										sound: "police_e06.WAV"},
 {type: "policeman_need_workers", 											sound: "police_e07.WAV"},
 {type: "policeman_enemies_are_coming", 								sound: "police_e08.WAV"},
 {type: "policeman_desease_can_start_at_any_moment", 		sound: "police_g01.WAV"},
 {type: "policeman_no_food_in_city", 										sound: "police_g02.WAV"},
 {type: "policeman_no_army", 														sound: "police_g03.WAV"},
 {type: "policeman_need_more_workers", 									sound: "police_g04.WAV"},
 {type: "policeman_gods_are_angry", 										sound: "police_g05.WAV"},
 {type: "policeman_no_army_2", 													sound: "police_g06.wav"},
 {type: "policeman_much_unemployments", 								sound: "police_g07.WAV"},
 {type: "policeman_low_entertainment", 									sound: "police_g08.WAV"},
 {type: "policeman_city_is_good", 											sound: "police_g09.WAV"},
 {type: "policeman_city_is_amazing", 										sound: "police_g10.WAV"},
 // reed
 {type: "", sound: "Reed_e01.wav"},
 {type: "", sound: "Reed_e02.wav"},
 // robber
 {type: "", sound: "robber_e01.wav"},
 {type: "", sound: "robber_e02.wav"},
 // scribe
 {type: "", sound: "scribe_e01.wav"},
 {type: "", sound: "scribe_g01.wav"},
 {type: "", sound: "scribe_g02.wav"},
 {type: "", sound: "scribe_g03.wav"},
 {type: "", sound: "scribe_g04.wav"},
 {type: "", sound: "scribe_g05.wav"},
 {type: "", sound: "scribe_g06.wav"},
 {type: "", sound: "scribe_g07.wav"},
 {type: "", sound: "scribe_g08.wav"},
 {type: "", sound: "scribe_g09.wav"},
 {type: "", sound: "scribe_g10.wav"},
 {type: "", sound: "senet_e01.wav"},
 {type: "", sound: "senet_g01.wav"},
 {type: "", sound: "senet_g02.wav"},
 {type: "", sound: "senet_g03.wav"},
 {type: "", sound: "senet_g04.wav"},
 {type: "", sound: "senet_g05.wav"},
 {type: "", sound: "senet_g06.wav"},
 {type: "", sound: "senet_g07.wav"},
 {type: "", sound: "senet_g08.wav"},
 {type: "", sound: "senet_g09.wav"},
 {type: "", sound: "senet_g10.wav"},
 {type: "", sound: "stone_e01.wav"},
 {type: "", sound: "stone_e02.wav"},
 // teacher
 {type: "teacher_festival_info", sound: "teacher_e01.wav"},
 {type: "teacher_desease_can_start_at_any_moment", sound: "teacher_g01.wav"},
 {type: "teacher_no_food_in_city", sound: "teacher_g02.wav"},
 {type: "teacher_city_not_safety", sound: "teacher_g03.wav"},
 {type: "teacher_need_workers", sound: "teacher_g04.wav"},
 {type: "teacher_gods_are_angry", sound: "teacher_g05.wav"},
 {type: "teacher_low_rating", sound: "teacher_g06.wav"},
 {type: "teacher_much_unemployments", sound: "teacher_g07.wav"},
 {type: "teacher_city_is_good", sound: "teacher_g08.wav"},
 {type: "teacher_city_much_better", sound: "teacher_g09.wav"},
 {type: "teacher_city_is_amazing", sound: "teacher_g10.wav"},
 //
 {type: "", sound: "thief_e01.wav"},
 {type: "", sound: "thief_e02.wav"},
 {type: "", sound: "thief_e03.wav"},
 {type: "", sound: "thief_e04.wav"},
 //
 {type: "", sound: "transport_e01.wav"},
 {type: "", sound: "transport_e02.wav"},
 {type: "", sound: "transport_e03.wav"},
 {type: "", sound: "transport_e04.wav"},
 //
 {type: "", sound: "vagrant_e01.wav"},
 {type: "", sound: "vagrant_e02.wav"},
 //
 {type: "", sound: "warship_e01.wav"},
 {type: "", sound: "warship_e02.wav"},
 {type: "", sound: "warship_e03.wav"},
 {type: "", sound: "warship_e04.wav"},
 {type: "", sound: "warship_e05.wav"},
 //
 {type: "", sound: "woodcutter_e01.wav"},
 {type: "", sound: "woodcutter_e02.wav"},
 //
 {type: "", sound: "zookeeper_e01.wav"},
 {type: "", sound: "zookeeper_e02.wav"},
 {type: "", sound: "zookeeper_e03.wav"},
 {type: "", sound: "zookeeper_e04.wav"},
 {type: "", sound: "zookeeper_e05.wav"},
 {type: "", sound: "zookeeper_e06.wav"},
 {type: "", sound: "zookeeper_e07.wav"},
 {type: "", sound: "zookeeper_e08.wav"},
 {type: "", sound: "zookeeper_e09.wav"},
 {type: "", sound: "zookeeper_e10.wav"}
]
