log_info("akhenaten: walker sounds started")

walker_sounds = [
  // apothecary
  {type: "apothecary_malaria_not_a_problem",             sound:"apothecary_e02.wav"},
  {type: "apothecary_malaria_outbreak_could_strike",     sound:"apothecary_e03.wav"},
  // artisan
  {type: "artisan_work_my_tools_need_for_monument",      sound:"artisan_e01.wav"},
  {type: "artisan_work_i_write_history_of_egypt",        sound:"artisan_e02.wav"},
  // barge
  {type: "barge_have_no_place_for_dock",                 sound:"barge_e01.wav"},
  {type: "barge_docked_wait_for_dockpushers",            sound:"barge_e02.wav"},
  {type: "barge_city_not_trades",                        sound:"barge_e03.wav"},
  {type: "barge_i_like_to_trage",                        sound:"barge_e04.wav"},
  {type: "barge_amazing_trades",                         sound:"barge_e05.wav"},
  // brick
  {type: "brick_bricklaying_time_at_monument",           sound:"brick_e01.wav"},
  {type: "brick_monument_will_be_strong",                sound:"brick_e02.wav"},
  // caravan
  {type: "caravan_city_not_trades",                      sound:"caravan_e01.wav"},
  {type: "caravan_buy_for_less_sell_for_more",           sound:"caravan_e02.wav"},
  {type: "caravan_its_my_life",                          sound:"caravan_e03.wav"},
  {type: "caravan_amazing_trades",                       sound:"caravan_e04.wav"},
  {type: "caravan_bad_trades",                           sound:"caravan_e05.wav"},
  // carpenter
  {type: "carpenter_work_my_tools_need_for_monument",    sound:"carpenter_e01.wav"},
  {type: "carpenter_this_monument_will_be_short",        sound:"carpenter_e02.wav"},
  // cartpusher
  {type: "cartpusher_no_one_available_to_unload",        sound:"cartpusher_e01.wav"},
  {type: "cartpusher_no_one_can_accept_these_goods",     sound:"cartpusher_e02.wav"},
  {type: "cartpusher_have_to_go_clear_across_city",      sound:"cartpusher_e03.wav"},
  // dancer
  {type: "dancer_festival_crowds",                       sound:"dancer_e01.wav"},
  {type: "dancer_many_people_taken_ill",                 sound:"dancer_g01.wav"},
  {type: "dancer_not_enough_food",                       sound:"dancer_g02.wav"},
  {type: "dancer_nothing_defends_city",                  sound:"dancer_g03.wav"},
  {type: "dancer_need_more_workers",                     sound:"dancer_g04.wav"},
  {type: "dancer_gods_are_angry",                        sound:"dancer_g05.wav"},
  {type: "dancer_reputation_is_low",                     sound:"dancer_g06.wav"},
  {type: "dancer_unemployment_is_high",                  sound:"dancer_g07.wav"},
  {type: "dancer_low_entertainment",                     sound:"dancer_g08.wav"},
  {type: "dancer_city_is_ok",                            sound:"dancer_g09.wav"},
  {type: "dancer_city_is_fantastic",                     sound:"dancer_g10.wav"},
  // dentist
  {type: "dentist_concerned_about_plague",               sound:"dentist_g01.wav"},
  {type: "dentist_no_food_in_city",                      sound:"dentist_g02.wav"},
  {type: "dentist_defenses_weak",                        sound:"dentist_g03.wav"},
  {type: "dentist_need_more_workers",                    sound:"dentist_g04.wav"},
  {type: "dentist_gods_are_angry",                       sound:"dentist_g05.wav"},
  {type: "dentist_reputation_is_low",                    sound:"dentist_g06.wav"},
  {type: "dentist_unemployment_is_high",                 sound:"dentist_g07.wav"},
  {type: "dentist_low_entertainment",                    sound:"dentist_g08.wav"},
  {type: "dentist_city_is_ok",                           sound:"dentist_g09.wav"},
  {type: "dentist_city_is_the_best",                     sound:"dentist_g10.wav"},
  // disease
  {type: "disease_oh_my_stomach_oh_my_head",             sound:"disease_e01.wav"},
  // dockpusher
  {type: "dockpusher_need_more_help",                    sound:"dockpusher_e01.wav"},
  {type: "dockpusher_wait_until_space_opens_up",         sound:"dockpusher_e02.wav"},
  {type: "dockpusher_cant_haul_goods_much_farther",      sound:"dockpusher_e03.wav"},
  // doctor
  {type: "doctor_plague_could_strike_us_dead",           sound:"doctor_e01.WAV"},
  {type: "doctor_concerned_about_plague",                sound:"doctor_g01.WAV"},
  {type: "doctor_no_food_in_city",                       sound:"doctor_g02.WAV"},
  {type: "doctor_defenses_weak",                         sound:"doctor_g03.WAV"},
  {type: "doctor_need_more_workers",                     sound:"doctor_g04.WAV"},
  {type: "doctor_gods_are_angry",                        sound:"doctor_g05.WAV"},
  {type: "doctor_reputation_is_low",                     sound:"doctor_g06.WAV"},
  {type: "doctor_unemployment_is_high",                  sound:"doctor_g07.WAV"},
  {type: "doctor_low_entertainment",                     sound:"doctor_g08.WAV"},
  {type: "doctor_city_is_ok",                            sound:"doctor_g09.WAV"},
  {type: "doctor_city_is_the_best",                      sound:"doctor_g10.WAV"},
  // embalmer
  {type: "embalmer_health_worsening",                    sound:"embalmer_e01.WAV"},
  {type: "embalmer_concerned_about_plague",              sound:"embalmer_g01.WAV"},
  {type: "embalmer_no_food_in_city",                     sound:"embalmer_g02.WAV"},
  {type: "embalmer_defenses_weak",                       sound:"embalmer_g03.WAV"},
  {type: "embalmer_need_more_workers",                   sound:"embalmer_g04.WAV"},
  {type: "embalmer_gods_are_angry",                      sound:"embalmer_g05.WAV"},
  {type: "embalmer_reputation_is_low",                   sound:"embalmer_g06.WAV"},
  {type: "embalmer_unemployment_is_high",                sound:"embalmer_g07.WAV"},
  {type: "embalmer_low_entertainment",                   sound:"embalmer_g08.WAV"},
  {type: "embalmer_city_is_ok",                          sound:"embalmer_g09.WAV"},
  {type: "embalmer_city_is_the_best",                    sound:"embalmer_g10.WAV"},
  // emigrant
  {type: "emigrant_cant_find_a_job_here",                sound:"emigrant_e01.wav"},
  {type: "emigrant_not_enough_food",                     sound:"emigrant_e02.wav"},
  {type: "emigrant_taxes_are_too_high",                  sound:"emigrant_e03.wav"},
  {type: "emigrant_cant_live_on_what_pay_here",          sound:"emigrant_e04.wav"},
  {type: "emigrant_not_enough_housing",                  sound:"emigrant_e05.wav"},
  // architect
  {type: "engineer_so_many_places_poor_condition",       sound:"engineer_e01.wav"},
  {type: "engineer_great_condition_of_city",             sound:"engineer_e02.wav"},
  {type: "engineer_concerned_about_plague",              sound:"engineer_g01.wav"},
  {type: "engineer_no_food_in_city",                     sound:"engineer_g02.wav"},
  {type: "engineer_defenses_weak",                       sound:"engineer_g03.wav"},
  {type: "engineer_need_more_workers",                   sound:"engineer_g04.wav"},
  {type: "engineer_gods_are_angry",                      sound:"engineer_g05.wav"},
  {type: "engineer_reputation_is_low",                   sound:"engineer_g06.wav"},
  {type: "engineer_unemployment_is_high",                sound:"engineer_g07.wav"},
  {type: "engineer_low_entertainment",                   sound:"engineer_g08.wav"},
  {type: "engineer_city_is_ok",                          sound:"engineer_g09.wav"},
  {type: "engineer_city_is_the_best",                    sound:"engineer_g10.wav"},
  // fireman
  {type: "fireman_busy_dousing_fire",                    sound:"fireman_e01.wav"},
  {type: "fireman_whole_city_could_burn_down",           sound:"fireman_e02.wav"},
  {type: "fireman_oh_thats_hot",                         sound:"fireman_e03.wav"},
  {type: "fireman_concerned_about_plague",               sound:"fireman_g01.wav"},
  {type: "fireman_no_food_in_city",                      sound:"fireman_g02.wav"},
  {type: "fireman_defenses_weak",                        sound:"fireman_g03.wav"},
  {type: "fireman_need_more_workers",                    sound:"fireman_g04.wav"},
  {type: "fireman_gods_are_angry",                       sound:"fireman_g05.wav"},
  {type: "fireman_reputation_is_low",                    sound:"fireman_g06.wav"},
  {type: "fireman_unemployment_is_high",                 sound:"fireman_g07.wav"},
  {type: "fireman_low_entertainment",                    sound:"fireman_g08.wav"},
  {type: "fireman_city_is_ok",                           sound:"fireman_g09.wav"},
  {type: "fireman_city_is_the_best",                     sound:"fireman_g10.wav"},
  // fishing
  {type: "fishing_sound1",                               sound:"fishing_e01.wav"},
  {type: "fishing_sound2",                               sound:"fishing_e02.wav"},
  {type: "fishing_sound3",                               sound:"fishing_e03.wav"},
  // governor
  {type: "governor_city_left_much_nobles",               sound:"governor_e01.WAV"},
  {type: "governor_festival_was_near",                   sound:"governor_e02.wav"},
  // guard
  {type: "guard_no_enemies_sighted",                     sound:"guard_e01.wav"},
  {type: "guard_ready_approaching_enemy",                sound:"guard_e02.wav"},
  {type: "guard_no_trouble_defeating_army",              sound:"guard_e03.wav"},
  {type: "guard_enemy_is_fierce",                        sound:"guard_e04.wav"},
  // hunt_ant
  {type: "hunt_ant_antelopes_no_match_for_us",           sound:"hunt_ant_e01.wav"},
  {type: "hunt_ant_steaks_for_everyone_tonight",         sound:"hunt_ant_e02.wav"},
  // hunt_bird
  {type: "hunt_bird_birds_are_wily",                     sound:"hunt_bird_e01.wav"},
  {type: "hunt_bird_birds_ready_for_roasting",           sound:"hunt_bird_e02.wav"},
  // hunt_ostrich
  {type: "hunt_ostrich_heads_in_the_sand",               sound:"hunt_ostrich_e01.wav"},
  {type: "hunt_ostrich_those_are_big_drumsticks",        sound:"hunt_ostrich_e02.wav"},
  // immigrant
  {type: "immigrant_im_new_here",                        sound:"immigrant_e01.wav"},
  {type: "immigrant_heard_there_is_a_job_here",          sound:"immigrant_e02.wav"},
  {type: "immigrant_city_has_plenty_of_food",            sound:"immigrant_e03.wav"},
  // juggler
  {type: "juggler_love_working_festival",                sound:"juggler_e01.wav"},
  {type: "juggler_never_seen_so_many_sick",              sound:"juggler_g01.wav"},
  {type: "juggler_no_food_in_city",                      sound:"juggler_g02.wav"},
  {type: "juggler_little_is_defending_city",             sound:"juggler_g03.wav"},
  {type: "juggler_job_vacancies_everywhere",             sound:"juggler_g04.wav"},
  {type: "juggler_gods_think_weve_forgotten_them",       sound:"juggler_g05.wav"},
  {type: "juggler_reputation_is_low",                    sound:"juggler_g06.wav"},
  {type: "juggler_high_unemployment",                    sound:"juggler_g07.wav"},
  {type: "juggler_low_entertainment",                    sound:"juggler_g08.wav"},
  {type: "juggler_city_is_ok",                           sound:"juggler_g09.wav"},
  {type: "juggler_city_is_amazing",                      sound:"juggler_g010.wav"},
  // Labor
  {type: "Labor_lot_of_people_need_jobs",                sound:"Labor_e01.wav"},
  {type: "Labor_cant_find_any_workers",                  sound:"Labor_e02.wav"},
  {type: "Labor_people_are_sick",                        sound:"Labor_g01.wav"},
  {type: "Labor_no_food_in_city",                        sound:"Labor_g02.wav"},
  {type: "Labor_defenses_are_weak",                      sound:"Labor_g03.wav"},
  {type: "Labor_without_workers_job_impossible",         sound:"Labor_g04.wav"},
  {type: "Labor_gods_are_angry",                         sound:"Labor_g05.wav"},
  {type: "Labor_reputation_is_low",                      sound:"Labor_g06.wav"},
  {type: "Labor_high_unemployment",                      sound:"Labor_g07.wav"},
  {type: "Labor_low_entertainment",                      sound:"Labor_g08.wav"},
  {type: "Labor_city_is_ok",                             sound:"Labor_g09.wav"},
  {type: "Labor_city_is_amazing",                        sound:"Labor_g10.wav"},
  // library
  {type: "library_read_about_festivals",                 sound: "library_e01.wav"},
  {type: "library_people_are_sick",                      sound: "library_g01.wav"},
  {type: "library_no_food_in_city",                      sound: "library_g02.wav"},
  {type: "library_defenses_are_weak",                    sound: "library_g03.wav"},
  {type: "library_need_more_workers",                    sound: "library_g04.wav"},
  {type: "library_gods_are_angry",                       sound: "library_g05.wav"},
  {type: "library_reputation_is_low",                    sound: "library_g06.wav"},
  {type: "library_high_unemployment",                    sound: "library_g07.wav"},
  {type: "library_low_entertainment",                    sound: "library_g08.wav"},
  {type: "library_city_is_ok",                           sound: "library_g09.wav"},
  {type: "library_city_is_amazing",                      sound: "library_g10.wav"},
  // magistrate
  {type: "magistrate_hope_ill_earn_funeral",             sound: "magistrate_e02.wav"},
  {type: "magistrate_no_crime_here",                     sound: "magistrate_e03.wav"},
  {type: "magistrate_only_petty_cases",                  sound: "magistrate_e04.wav"},
  {type: "magistrate_streets_are_unsafe",                sound: "magistrate_e05.wav"},
  {type: "magistrate_danger_of_plague",                  sound: "magistrate_g01.wav"},
  {type: "magistrate_no_food_in_city",                   sound: "magistrate_g02.wav"},
  {type: "magistrate_defenses_are_weak",                 sound: "magistrate_g03.wav"},
  {type: "magistrate_need_more_workers",                 sound: "magistrate_g04.wav"},
  {type: "magistrate_gods_are_angry",                    sound: "magistrate_g05.wav"},
  {type: "magistrate_reputation_is_low",                 sound: "magistrate_g06.wav"},
  {type: "magistrate_high_unemployment",                 sound: "magistrate_g07.wav"},
  {type: "magistrate_low_entertainment",                 sound: "magistrate_g08.wav"},
  {type: "magistrate_city_is_ok",                        sound: "magistrate_g09.wav"},
  {type: "magistrate_city_is_amazing",                   sound: "magistrate_g10.wav"},
  // marketboy
  {type: "marketboy_these_baskets_are_too_heavy",        sound: "marketboy_e01.wav"},
  {type: "marketboy_bossy_lady_makes_me_carry_goods",    sound: "marketboy_e02.wav"},
  {type: "marketboy_one_day_ill_run_the_bazaar",         sound: "marketboy_e03.wav"},
  // mkt_buyer
  {type: "mkt_buyer_going_to_get_goods",                 sound: "mkt_buyer_e01.wav"},
  {type: "mkt_buyer_taking_goods_to_bazaar",             sound: "mkt_buyer_e02.wav"},
  {type: "mkt_buyer_danger_of_plague",                   sound: "mkt_buyer_g01.wav"},
  {type: "mkt_buyer_no_food_in_city",                    sound: "mkt_buyer_g02.wav"},
  {type: "mkt_buyer_defenses_are_weak",                  sound: "mkt_buyer_g03.wav"},
  {type: "mkt_buyer_need_more_workers",                  sound: "mkt_buyer_g04.wav"},
  {type: "mkt_buyer_gods_are_angry",                     sound: "mkt_buyer_g05.wav"},
  {type: "mkt_buyer_reputation_is_low",                  sound: "mkt_buyer_g06.wav"},
  {type: "mkt_buyer_high_unemployment",                  sound: "mkt_buyer_g07.wav"},
  {type: "mkt_buyer_low_entertainment",                  sound: "mkt_buyer_g08.wav"},
  {type: "mkt_buyer_city_is_ok",                         sound: "mkt_buyer_g09.wav"},
  {type: "mkt_buyer_city_is_amazing",                    sound: "mkt_buyer_g10.wav"},
  // mkt_seller
  {type: "",                                             sound: "mkt_seller_e01.wav"},
  {type: "",                                             sound: "mkt_seller_e02.wav"},
  // musician
  {type: "musician_danger_of_plague",                    sound: "musician_g01.wav"},
  {type: "musician_no_food_in_city",                     sound: "musician_g02.wav"},
  {type: "musician_defenses_are_weak",                   sound: "musician_g03.wav"},
  {type: "musician_need_more_workers",                   sound: "musician_g04.wav"},
  {type: "musician_gods_are_angry",                      sound: "musician_g05.wav"},
  {type: "musician_reputation_is_low",                   sound: "musician_g06.wav"},
  {type: "musician_high_unemployment",                   sound: "musician_g07.wav"},
  {type: "musician_low_entertainment",                   sound: "musician_g08.wav"},
  {type: "musician_city_is_ok",                          sound: "musician_g09.wav"},
  {type: "musician_city_is_amazing",                     sound: "musician_g10.wav"},
  // pharaoh
  {type: "pharaoh_how_impertinent",                      sound: "pharaoh_e01.wav"},
  // policeman
  {type: "policeman_low_crime_level",                    sound: "police_e01.WAV"},
  {type: "policeman_usual_crime_level",                  sound: "police_e02.WAV"},
  {type: "policeman_very_low_crime_level",               sound: "police_e03.WAV"},
  {type: "policeman_iam_too_busy_that_talk",             sound: "police_e04.WAV"},
  {type: "policeman_i_hope_my_work_is_need",             sound: "police_e05.WAV"},
  {type: "policeman_city_not_safety",                    sound: "police_e06.WAV"},
  {type: "policeman_need_workers",                       sound: "police_e07.WAV"},
  {type: "policeman_enemies_are_coming",                 sound: "police_e08.WAV"},
  {type: "policeman_desease_can_start_at_any_moment",    sound: "police_g01.WAV"},
  {type: "policeman_no_food_in_city",                    sound: "police_g02.WAV"},
  {type: "policeman_no_army",                            sound: "police_g03.WAV"},
  {type: "policeman_need_more_workers",                  sound: "police_g04.WAV"},
  {type: "policeman_gods_are_angry",                     sound: "police_g05.WAV"},
  {type: "policeman_no_army_2",                          sound: "police_g06.wav"},
  {type: "policeman_much_unemployments",                 sound: "police_g07.WAV"},
  {type: "policeman_low_entertainment",                  sound: "police_g08.WAV"},
  {type: "policeman_city_is_good",                       sound: "police_g09.WAV"},
  {type: "policeman_city_is_amazing",                    sound: "police_g10.WAV"},
  // priest_bast
  {type: "priest_bast_festival",                         sound: "priest_bast_e01.wav"},
  {type: "priest_bast_people_could_turn_to_crime",       sound: "priest_bast_e02.wav"},
  {type: "priest_bast_so_little_diversion",              sound: "priest_bast_e03.wav"},
  {type: "priest_bast_power_to_heal_the_sick",           sound: "priest_bast_e04.wav"},
  {type: "priest_bast_danger_of_plague",                 sound: "priest_bast_g01.wav"},
  {type: "priest_bast_no_food_in_city",                  sound: "priest_bast_g02.wav"},
  {type: "priest_bast_defenses_are_weak",                sound: "priest_bast_g03.wav"},
  {type: "priest_bast_need_more_workers",                sound: "priest_bast_g04.wav"},
  {type: "priest_bast_gods_are_angry",                   sound: "priest_bast_g05.wav"},
  {type: "priest_bast_reputation_is_low",                sound: "priest_bast_g06.wav"},
  {type: "priest_bast_high_unemployment",                sound: "priest_bast_g07.wav"},
  {type: "priest_bast_low_entertainment",                sound: "priest_bast_g08.wav"},
  {type: "priest_bast_city_is_ok",                       sound: "priest_bast_g09.wav"},
  {type: "priest_bast_city_is_amazing",                  sound: "priest_bast_g10.wav"},
  // priest_osiris
  {type: "priest_osiris_festival",                       sound: "priest_osiris_e01.wav"},
  {type: "priest_osiris_punish_with_low_flood",          sound: "priest_osiris_e02.wav"},
  {type: "priest_osiris_danger_of_plague",               sound: "priest_osiris_g01.wav"},
  {type: "priest_osiris_no_food_in_city",                sound: "priest_osiris_g02.wav"},
  {type: "priest_osiris_defenses_are_weak",              sound: "priest_osiris_g03.wav"},
  {type: "priest_osiris_need_more_workers",              sound: "priest_osiris_g04.wav"},
  {type: "priest_osiris_gods_are_angry",                 sound: "priest_osiris_g05.wav"},
  {type: "priest_osiris_reputation_is_low",              sound: "priest_osiris_g06.wav"},
  {type: "priest_osiris_high_unemployment",              sound: "priest_osiris_g07.wav"},
  {type: "priest_osiris_low_entertainment",              sound: "priest_osiris_g08.wav"},
  {type: "priest_osiris_city_is_ok",                     sound: "priest_osiris_g09.wav"},
  {type: "priest_osiris_city_is_amazing",                sound: "priest_osiris_g10.wav"},
  // priest_ptah
  {type: "priest_ptah_festival",                         sound: "priest_ptah_e01.wav"},
  {type: "priest_ptah_industry_needs_workers",           sound: "priest_ptah_e02.wav"},
  {type: "priest_ptah_danger_of_plague",                 sound: "priest_ptah_g01.wav"},
  {type: "priest_ptah_no_food_in_city",                  sound: "priest_ptah_g02.wav"},
  {type: "priest_ptah_defenses_are_weak",                sound: "priest_ptah_g03.wav"},
  {type: "priest_ptah_need_more_workers",                sound: "priest_ptah_g04.wav"},
  {type: "priest_ptah_gods_are_angry",                   sound: "priest_ptah_g05.wav"},
  {type: "priest_ptah_reputation_is_low",                sound: "priest_ptah_g06.wav"},
  {type: "priest_ptah_high_unemployment",                sound: "priest_ptah_g07.wav"},
  {type: "priest_ptah_low_entertainment",                sound: "priest_ptah_g08.wav"},
  {type: "priest_ptah_city_is_amazing",                  sound: "priest_ptah_g10.wav"},
  // priest_ra
  {type: "priest_ra_festival",                           sound: "priest_ra_e01.wav"},
  {type: "priest_ra_city_is_an_embarrasment",            sound: "priest_ra_e02.wav"},
  {type: "priest_ra_danger_of_plague",                   sound: "priest_ra_g01.wav"},
  {type: "priest_ra_no_food_in_city",                    sound: "priest_ra_g02.wav"},
  {type: "priest_ra_defenses_are_weak",                  sound: "priest_ra_g03.wav"},
  {type: "priest_ra_need_more_workers",                  sound: "priest_ra_g04.wav"},
  {type: "priest_ra_gods_are_angry",                     sound: "priest_ra_g05.wav"},
  {type: "priest_ra_reputation_is_low",                  sound: "priest_ra_g06.wav"},
  {type: "priest_ra_high_unemployment",                  sound: "priest_ra_g07.wav"},
  {type: "priest_ra_low_entertainment",                  sound: "priest_ra_g08.wav"},
  {type: "priest_ra_city_is_ok",                         sound: "priest_ra_g09.wav"},
  {type: "priest_ra_city_is_amazing",                    sound: "priest_ra_g10.wav"},
  // priest_seth
  {type: "priest_seth_festival",                         sound: "priest_seth_e01.wav"},
  {type: "priest_seth_enemies_approaching",              sound: "priest_seth_e02.wav"},
  {type: "priest_seth_danger_of_plague",                 sound: "priest_seth_g01.wav"},
  {type: "priest_seth_no_food_in_city",                  sound: "priest_seth_g02.wav"},
  {type: "priest_seth_defenses_are_weak",                sound: "priest_seth_g03.wav"},
  {type: "priest_seth_need_more_workers",                sound: "priest_seth_g04.wav"},
  {type: "priest_seth_gods_are_angry",                   sound: "priest_seth_g05.wav"},
  {type: "priest_seth_reputation_is_low",                sound: "priest_seth_g06.wav"},
  {type: "priest_seth_high_unemployment",                sound: "priest_seth_g07.wav"},
  {type: "priest_seth_low_entertainment",                sound: "priest_seth_g08.wav"},
  {type: "priest_seth_city_is_ok",                       sound: "priest_seth_g09.wav"},
  {type: "priest_seth_city_is_amazing",                  sound: "priest_seth_g10.wav"},
  // reed
  {type: "reed_to_the_marsh_i_march",                    sound: "REED_E01.WAV"},
  {type: "reed_will_make_some_fine_papyrus",             sound: "REED_E02.WAV"},
  // robber
  {type: "robber_gold_should_be_for_living",             sound: "robber_e01.wav"},
  {type: "robber_just_think_of_the_fortune",             sound: "robber_e02.wav"},
  // scribe
  {type: "scribe_these_festivals",                       sound: "scribe_e01.wav"},
  {type: "scribe_plague_could_break_out",                sound: "scribe_g01.wav"},
  {type: "scribe_no_food_in_city",                       sound: "scribe_g02.wav"},
  {type: "scribe_defenses_are_weak",                     sound: "scribe_g03.wav"},
  {type: "scribe_need_more_workers",                     sound: "scribe_g04.wav"},
  {type: "scribe_gods_are_angry",                        sound: "scribe_g05.wav"},
  {type: "scribe_reputation_is_low",                     sound: "scribe_g06.wav"},
  {type: "scribe_high_unemployment",                     sound: "scribe_g07.wav"},
  {type: "scribe_low_entertainment",                     sound: "scribe_g08.wav"},
  {type: "scribe_city_is_ok",                            sound: "scribe_g09.wav"},
  {type: "scribe_city_is_amazing",                       sound: "scribe_g10.wav"},
  // senet
  {type: "senet_get_your_beer_here",                     sound: "senet_e01.wav"},
  {type: "senet_risk_of_plague",                         sound: "senet_g01.wav"},
  {type: "senet_no_food_in_city",                        sound: "senet_g02.wav"},
  {type: "senet_defenses_are_weak",                      sound: "senet_g03.wav"},
  {type: "senet_need_more_workers",                      sound: "senet_g04.wav"},
  {type: "senet_gods_are_angry",                         sound: "senet_g05.wav"},
  {type: "senet_reputation_is_low",                      sound: "senet_g06.wav"},
  {type: "senet_high_unemployment",                      sound: "senet_g07.wav"},
  {type: "senet_low_entertainment",                      sound: "senet_g08.wav"},
  {type: "senet_city_is_ok",                             sound: "senet_g09.wav"},
  {type: "senet_city_is_amazing",                        sound: "senet_g10.wav"},
  // stone
  {type: "stone_going_to_monument",                      sound: "stone_e01.wav"},
  {type: "stone_my_work_will_endure",                    sound: "stone_e02.wav"},
  // taxman
  {type: "taxman_need_more_tax_collectors",              sound: "taxman_e01.wav"},
  {type: "taxman_the_nicer_the_houses",                  sound: "taxman_e02.wav"},
  {type: "taxman_hate_rundown_houses",                   sound: "taxman_e03.wav"},
  {type: "taxman_danger_of_plague",                      sound: "taxman_g01.wav"},
  {type: "taxman_no_food_in_city",                       sound: "taxman_g02.wav"},
  {type: "taxman_defenses_are_weak",                     sound: "taxman_g03.wav"},
  {type: "taxman_need_more_workers",                     sound: "taxman_g04.wav"},
  {type: "taxman_gods_are_angry",                        sound: "taxman_g05.wav"},
  {type: "taxman_reputation_is_low",                     sound: "taxman_g06.wav"},
  {type: "taxman_high_unemployment",                     sound: "taxman_g07.wav"},
  {type: "taxman_low_entertainment",                     sound: "taxman_g08.wav"},
  {type: "taxman_city_is_ok",                            sound: "taxman_g09.wav"},
  {type: "taxman_city_is_amazing",                       sound: "taxman_g10.wav"},
  // teacher
  {type: "teacher_festival_info",                        sound: "teacher_e01.wav"},
  {type: "teacher_desease_can_start_at_any_moment",      sound: "teacher_g01.wav"},
  {type: "teacher_no_food_in_city",                      sound: "teacher_g02.wav"},
  {type: "teacher_city_not_safety",                      sound: "teacher_g03.wav"},
  {type: "teacher_need_workers",                         sound: "teacher_g04.wav"},
  {type: "teacher_gods_are_angry",                       sound: "teacher_g05.wav"},
  {type: "teacher_low_rating",                           sound: "teacher_g06.wav"},
  {type: "teacher_much_unemployments",                   sound: "teacher_g07.wav"},
  {type: "teacher_city_is_good",                         sound: "teacher_g08.wav"},
  {type: "teacher_city_much_better",                     sound: "teacher_g09.wav"},
  {type: "teacher_city_is_amazing",                      sound: "teacher_g10.wav"},
  // thief
  {type: "thief_maybe_stealing_will_get_attention",      sound: "thief_e01.wav"},
  {type: "thief_i_take_what_i_want",                     sound: "thief_e02.wav"},
  {type: "thief_more_profitable_than_other_jobs",        sound: "thief_e03.wav"},
  {type: "thief_take_take_take",                         sound: "thief_e04.wav"},
  // transport
  {type: "transport_must_protect_our_ship",              sound: "transport_e01.wav"},
  {type: "transport_enemy_is_here",                      sound: "transport_e02.wav"},
  {type: "transport_were_prepared",                      sound: "transport_e03.wav"},
  {type: "transport_ready_if_need_arises",               sound: "transport_e04.wav"},
  // vagrant
  {type: "vagrant_kicked_out_of_my_home",                sound: "vagrant_e01.wav"},
  {type: "vagrant_cant_find_a_place_to_live",            sound: "vagrant_e02.wav"},
  // warship
  {type: "warship_well_fight_to_the_death",              sound: "warship_e01.wav"},
  {type: "warship_enemy_is_too_much_for_us",             sound: "warship_e02.wav"},
  {type: "warship_enemies_coming_this_way",              sound: "warship_e03.wav"},
  {type: "warship_ready_to_attack_invaders",             sound: "warship_e04.wav"},
  {type: "warship_ready_if_foes_come",                   sound: "warship_e05.wav"},
  // water
  {type: "water_danger_of_plague",                       sound: "water_g01.wav"},
  {type: "water_no_food_in_city",                        sound: "water_g02.wav"},
  {type: "water_defenses_are_weak",                      sound: "water_g03.wav"},
  {type: "water_need_more_workers",                      sound: "water_g04.wav"},
  {type: "water_gods_are_angry",                         sound: "water_g05.wav"},
  {type: "water_reputation_is_low",                      sound: "water_g06.wav"},
  {type: "water_high_unemployment",                      sound: "water_g07.wav"},
  {type: "water_low_entertainment",                      sound: "water_g08.wav"},
  {type: "water_city_is_ok",                             sound: "water_g09.wav"},
  {type: "water_city_is_amazing",                        sound: "water_g10.wav"},
  // woodcutter
  {type: "woodcutter_hard_days_logging",                 sound: "woodcutter_e01.wav"},
  {type: "woodcutter_timber_put_to_good_use",            sound: "woodcutter_e02.wav"},
  // worker
  {type: "worker_im_ready_to_work",                      sound: "worker_e02.wav"},
  {type: "worker_fields_under_water",                    sound: "worker_e03.wav"},
  {type: "worker_danger_of_plague",                      sound: "worker_g01.wav"},
  {type: "worker_no_food_in_city",                       sound: "worker_g02.wav"},
  {type: "worker_defenses_are_weak",                     sound: "worker_g03.wav"},
  {type: "worker_need_more_workers",                     sound: "worker_g04.wav"},
  {type: "worker_gods_are_angry",                        sound: "worker_g05.wav"},
  {type: "worker_reputation_is_low",                     sound: "worker_g06.wav"},
  {type: "worker_high_unemployment",                     sound: "worker_g07.wav"},
  {type: "worker_low_entertainment",                     sound: "worker_g08.wav"},
  {type: "worker_city_is_ok",                            sound: "worker_g09.wav"},
  {type: "worker_city_is_amazing",                       sound: "worker_g10.wav"},
  // zookeeper
  {type: "zookeeper_danger_of_plague",                   sound: "zookeeper_e01.wav"},
  {type: "zookeeper_no_food_in_city",                    sound: "zookeeper_e02.wav"},
  {type: "zookeeper_defenses_are_weak",                  sound: "zookeeper_e03.wav"},
  {type: "zookeeper_need_more_workers",                  sound: "zookeeper_e04.wav"},
  {type: "zookeeper_gods_are_angry",                     sound: "zookeeper_e05.wav"},
  {type: "zookeeper_reputation_is_low",                  sound: "zookeeper_e06.wav"},
  {type: "zookeeper_high_unemployment",                  sound: "zookeeper_e07.wav"},
  {type: "zookeeper_low_entertainment",                  sound: "zookeeper_e08.wav"},
  {type: "zookeeper_city_is_ok",                         sound: "zookeeper_e09.wav"},
  {type: "zookeeper_city_is_amazing",                    sound: "zookeeper_e10.wav"}
]
