#include "js_constants.h"

#include "js_defines.h"

#include "input/hotkey.h"
#include "mujs/mujs.h"
#include "window/file_dialog.h"

#include "sound/city.h"

void js_register_game_constants(js_State *J) {
   REGISTER_GLOBAL_CONSTANT(J, FILE_TYPE_SAVED_GAME);
   REGISTER_GLOBAL_CONSTANT(J, FILE_DIALOG_LOAD);
}

void js_register_city_sound_constants(js_State *J) {
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_HOUSE_SLUM);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_HOUSE_POOR);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_HOUSE_MEDIUM);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_HOUSE_GOOD);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_HOUSE_POSH);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_BOOTH);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_BANDSTAND);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_PAVILION);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_SENET_HOUSE);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_JUGGLER_SCHOOL);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_DANCE_SCHOOL);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_CONSERVATORY);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_GARDEN);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_APOTHECARY);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_PHYSICIAN);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_MORTUARY);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_TOWER);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_TEMPLE_OSIRIS);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_TEMPLE_RA);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_TEMPLE_PTAH);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_TEMPLE_SETH);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_TEMPLE_BAST);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_SHRINE_OSIRIS);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_SHRINE_RA);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_SHRINE_PTAH);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_SHRINE_SETH);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_SHRINE_BAST);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_MARKET);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_GRANARY);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_STORAGE_YARD);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_SHIPYARD);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_DOCK);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_WHARF);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_PALACE);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_ENGINEERS_POST);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_FORUM);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_WATER_SUPPLY);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_WELL);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_BURNING_RUIN);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_GRAIN_FARM);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_FIG_FARM);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_QUARRY);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_GOLD_MINE);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_TIMBER_YARD);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_CLAY_PIT);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_WEAPONS_WORKSHOP);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_POTTERY_WORKSHOP);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_EMPTY_LAND);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_RIVER);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_HUNTER_LOUDGE);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_POLICE);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_ROCK);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_STATUE);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_TAX_COLLECTOR);
}