#include "js_constants.h"

#include "js_defines.h"

#include "input/hotkey.h"
#include "mujs/mujs.h"
#include "window/file_dialog.h"
#include "overlays/city_overlay_fwd.h"
#include "building/building.h"
#include "graphics/image_desc.h"
#include "graphics/image_groups.h"

#include "sound/city.h"

void js_register_game_constants(js_State *J) {
   REGISTER_GLOBAL_CONSTANT(J, FILE_TYPE_SAVED_GAME);
   REGISTER_GLOBAL_CONSTANT(J, FILE_DIALOG_LOAD);
}

void js_register_city_images(js_State *J) {
#define REGISTER_IMG(a, b) REGISTER_GLOBAL_CONSTANT(J, a);
#include "graphics/indexes.h"
#undef REGISTER_IMG
}

void js_register_collection_images(js_State *J) {
   REGISTER_GLOBAL_CONSTANT(J, PACK_UNLOADED);
   REGISTER_GLOBAL_CONSTANT(J, PACK_TERRAIN);
   REGISTER_GLOBAL_CONSTANT(J, PACK_GENERAL);
   REGISTER_GLOBAL_CONSTANT(J, PACK_SPR_MAIN);
   REGISTER_GLOBAL_CONSTANT(J, PACK_SPR_AMBIENT);
   REGISTER_GLOBAL_CONSTANT(J, PACK_EMPIRE);
   REGISTER_GLOBAL_CONSTANT(J, PACK_FONT);
   REGISTER_GLOBAL_CONSTANT(J, PACK_TEMPLE);
   REGISTER_GLOBAL_CONSTANT(J, PACK_MONUMENT);
   REGISTER_GLOBAL_CONSTANT(J, PACK_ENEMY)
   REGISTER_GLOBAL_CONSTANT(J, PACK_EXPANSION);
   REGISTER_GLOBAL_CONSTANT(J, PACK_EXPANSION_SPR);
   REGISTER_GLOBAL_CONSTANT(J, PACK_MASTABA);
   REGISTER_GLOBAL_CONSTANT(J, PACK_CUSTOM);
}

void js_register_city_walkers(js_State *J) {
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_NONE);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_IMMIGRANT);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_EMIGRANT);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_HOMELESS);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_CART_PUSHER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_LABOR_SEEKER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_EXPLOSION);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_TAX_COLLECTOR);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_ENGINEER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_STORAGE_YARD_DELIVERCART);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_FIREMAN);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_FORT_ARCHER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_FORT_SPEARMAN);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_FORT_CHARIOT);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_FORT_STANDARD);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_JUGGLER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_MUSICIAN);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_DANCER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_CHARIOTEER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_TRADE_CARAVAN);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_TRADE_SHIP);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_TRADE_CARAVAN_DONKEY);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_PROTESTER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_CRIMINAL);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_RIOTER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_FISHING_BOAT);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_MARKET_TRADER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_PRIEST);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_TEACHER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_SCRIBER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_LIBRARIAN);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_DENTIST);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_PHYSICIAN);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_HERBALIST);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_EMBALMER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_WORKER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_MAP_FLAG);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_FLOTSAM);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_DOCKER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_MARKET_BUYER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_NOBLES);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_INDIGENOUS_NATIVE);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_TOWER_SENTRY);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_ENEMY43_SPEAR);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_ENEMY44_SWORD);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_ENEMY45_SWORD);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_ENEMY46_CAMEL);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_ENEMY47_ELEPHANT);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_ENEMY48_CHARIOT);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_ENEMY49_FAST_SWORD);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_ENEMY50_SWORD);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_ENEMY51_SPEAR);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_ENEMY52_MOUNTED_ARCHER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_ENEMY53_AXE);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_ENEMY54_GLADIATOR);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_ENEMY_CAESAR_JAVELIN);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_ENEMY_CAESAR_MOUNTED);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_ENEMY_CAESAR_LEGIONARY);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_NATIVE_TRADER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_ARROW);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_JAVELIN);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_BOLT);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_BALLISTA);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_CREATURE);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_MISSIONARY);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_FISHING_POINT);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_DELIVERY_BOY);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_SHIPWRECK);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_SHEEP);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_OSTRICH);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_ZEBRA);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_SPEAR);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_HIPPODROME_HORSES);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_OSTRICH_HUNTER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_HUNTER_ARROW);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_LUMBERJACK);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_PHARAOH);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_GOVERNOR);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_WARSHIP);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_CROCODILE);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_HIPPO);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_WORKER_PH);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_WATER_CARRIER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_POLICEMAN);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_MAGISTRATE);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_REED_GATHERER);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_FESTIVAL_PRIEST);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_92);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_93);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_FISHING_SPOT);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_100);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_101);
   REGISTER_GLOBAL_CONSTANT(J, FIGURE_102);
}

void js_register_city_sound_constants(js_State *J) {
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_HOUSE_SLUM);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_HOUSE_POOR);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_HOUSE_MEDIUM);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_HOUSE_GOOD);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_HOUSE_POSH);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_BOOTH);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_BANDSTAND);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_PAVILION);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_SENET_HOUSE);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_JUGGLER_SCHOOL);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_DANCE_SCHOOL);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_CONSERVATORY);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_GARDEN);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_APOTHECARY);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_PHYSICIAN);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_MORTUARY);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_TOWER);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_TEMPLE_OSIRIS);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_TEMPLE_RA);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_TEMPLE_PTAH);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_TEMPLE_SETH);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_TEMPLE_BAST);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_SHRINE_OSIRIS);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_SHRINE_RA);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_SHRINE_PTAH);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_SHRINE_SETH);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_SHRINE_BAST);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_MARKET);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_GRANARY);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_STORAGE_YARD);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_SHIPYARD);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_DOCK);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_WHARF);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_PALACE);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_ENGINEERS_POST);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_FORUM);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_WATER_SUPPLY);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_WELL);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_BURNING_RUIN);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_GRAIN_FARM);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_FIG_FARM);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_QUARRY);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_GOLD_MINE);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_TIMBER_YARD);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_CLAY_PIT);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_WEAPONS_WORKSHOP);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_POTTERY_WORKSHOP);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_EMPTY_LAND);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_RIVER);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_HUNTER_LOUDGE);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_POLICE);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_ROCK);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_STATUE);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_TAX_COLLECTOR);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_DENTIST);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_MANSION);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_TREE);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_WATER);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_SHRUB);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_CANAL);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_MEADOW);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_FLOODPLAIN);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_MARSHLAND);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_CHICKFARM);
   REGISTER_GLOBAL_CONSTANT(J, SOUND_CHANNEL_CITY_COWFARM);
}

void js_register_city_buildings(js_State *J) {
#define REGISTER_BLD(a, b) REGISTER_GLOBAL_CONSTANT(J, a);
#include "building/building_type_indexes.h"
#undef REGISTER_BLD
}

void js_register_city_overlays(js_State *J) {
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_NONE);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_WATER);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_RELIGION);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_FIRE);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_DAMAGE);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_CRIME);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_ENTERTAINMENT);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_BOOTH);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_BANDSTAND);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_PAVILION);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_HIPPODROME);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_EDUCATION);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_SCRIBAL_SCHOOL);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_LIBRARY);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_ACADEMY);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_APOTHECARY);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_DENTIST);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_PHYSICIAN);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_MORTUARY);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_TAX_INCOME);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_FOOD_STOCKS);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_DESIRABILITY);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_WORKERS_UNUSED);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_NATIVE);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_PROBLEMS);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_RELIGION_OSIRIS);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_RELIGION_RA);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_RELIGION_PTAH);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_RELIGION_SETH);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_RELIGION_BAST);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_FERTILITY);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_BAZAAR_ACCESS);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_ROUTING);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_HEALTH);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_LABOR);
   REGISTER_GLOBAL_CONSTANT(J, OVERLAY_COUTHOUSE);
}