#pragma once

/**
 * @file
 * Type definitions for buildings
 */

enum e_building_type {
#define REGISTER_BLD(a, b) a = b,
#include "building_type_indexes.h"
#undef REGISTER_BLD
};

enum e_house_level {
    HOUSE_CRUDE_HUT = 0,
    HOUSE_STURDY_HUT = 1,
    HOUSE_MEAGER_SHANTY = 2,
    HOUSE_COMMON_SHANTY = 3,
    HOUSE_ROUGH_COTTAGE = 4,
    HOUSE_ORDINARY_COTTAGE = 5,
    HOUSE_MODEST_HOMESTEAD = 6,
    HOUSE_SPACIOUS_HOMESTEAD = 7,
    HOUSE_MODEST_APARTMENT = 8,
    HOUSE_SPACIOUS_APARTMENT = 9,
    HOUSE_COMMON_RESIDENCE = 10,
    HOUSE_SPACIOUS_RESIDENCE = 11,
    HOUSE_ELEGANT_RESIDENCE = 12,
    HOUSE_FANCY_RESIDENCE = 13,
    HOUSE_COMMON_MANOR = 14,
    HOUSE_SPACIOUS_MANOR = 15,
    HOUSE_ELEGANT_MANOR = 16,
    HOUSE_STATELY_MANOR = 17,
    HOUSE_MODEST_ESTATE = 18,
    HOUSE_PALATIAL_ESTATE = 19,
};