#ifndef GRAPHICS_IMAGE_GROUP_EDITOR_H
#define GRAPHICS_IMAGE_GROUP_EDITOR_H

// TODO?

#define GROUP_EDITOR_SCENARIO_IMAGE 0, 22
#define GROUP_EDITOR_BUILDING_CROPS 0, 23
#define GROUP_EDITOR_EMPIRE_MAP 0, 47
#define GROUP_EDITOR_SIDE_PANEL 0, 80
#define GROUP_EDITOR_RESOURCE_ICONS 0, 129
#define GROUP_EDITOR_EMPIRE_PANELS 0, 172
#define GROUP_EDITOR_EMPIRE_RESOURCES 0, 173
#define GROUP_EDITOR_BUILDING_NATIVE 0, 183
#define GROUP_EDITOR_EMPIRE_FOREIGN_CITY 0, 223
#define GROUP_EDITOR_TRADE_AMOUNT 0, 243

#endif // GRAPHICS_IMAGE_GROUP_EDITOR_H
