#pragma once

enum e_advisor {
    ADVISOR_NONE = 0,
    ADVISOR_LABOR = 1,
    ADVISOR_MILITARY = 2,
    ADVISOR_IMPERIAL = 3,
    ADVISOR_RATINGS = 4,
    ADVISOR_TRADE = 5,
    ADVISOR_POPULATION = 6,
    ADVISOR_HEALTH = 7,
    ADVISOR_EDUCATION = 8,
    ADVISOR_ENTERTAINMENT = 9,
    ADVISOR_RELIGION = 10,
    ADVISOR_FINANCIAL = 11,
    ADVISOR_CHIEF = 12,
    ADVISOR_MONUMENTS = 13,
    ADVISOR_HOUSING = 19,
    ADVISOR_MAX
};

enum e_low_mood_reason {
    LOW_MOOD_NONE = 0,
    LOW_MOOD_NO_FOOD = 1,
    LOW_MOOD_NO_JOBS = 2,
    LOW_MOOD_HIGH_TAXES = 3,
    LOW_MOOD_LOW_WAGES = 4,
    LOW_MOOD_MANY_TENTS = 5,
};

enum e_no_immigratoion_reason {
    NO_IMMIGRATION_LOW_WAGES = 0,
    NO_IMMIGRATION_NO_JOBS = 1,
    NO_IMMIGRATION_NO_FOOD = 2,
    NO_IMMIGRATION_HIGH_TAXES = 3,
    NO_IMMIGRATION_MANY_TENTS = 4,
    NO_IMMIGRATION_LOW_MOOD = 5
};

enum e_trade_status {
    TRADE_STATUS_NONE = 0,
    TRADE_STATUS_IMPORT = 1,
    TRADE_STATUS_EXPORT = 2,
    TRADE_STATUS_IMPORT_AS_NEEDED = 3,
    TRADE_STATUS_EXPORT_SURPLUS = 4,
};

enum e_availability {
    NOT_AVAILABLE_YET = -1,
    NOT_AVAILABLE = 0,
    AVAILABLE = 1,
};