#pragma once

enum e_labor_category {
    LABOR_CATEGORY_NONE = -1,
    LABOR_CATEGORY_FOOD_PRODUCTION = 0, // todo: wrong index...
    LABOR_CATEGORY_INDUSTRY_COMMERCE = 1,
    LABOR_CATEGORY_ENTERTAINMENT = 2,
    LABOR_CATEGORY_RELIGION = 3,
    LABOR_CATEGORY_EDUCATION = 4,
    LABOR_CATEGORY_WATER_HEALTH = 5,
    LABOR_CATEGORY_INFRASTRUCTURE = 6,
    LABOR_CATEGORY_GOVERNMENT = 7,
    LABOR_CATEGORY_MILITARY = 8,
    LABOR_CATEGORY_SIZE = 10,
};