#pragma once

#include "sound/channel.h"

class building;

enum e_sound_dir { 
    SOUND_DIRECTION_LEFT = 0,
    SOUND_DIRECTION_CENTER = 2,
    SOUND_DIRECTION_RIGHT = 4
};

enum e_sound_channel_city {
    SOUND_CHANNEL_CITY_START = SOUND_CHANNEL_CITY_MIN,
    SOUND_CHANNEL_CITY_HOUSE_SLUM = SOUND_CHANNEL_CITY_MIN,
    SOUND_CHANNEL_CITY_HOUSE_POOR,
    SOUND_CHANNEL_CITY_HOUSE_MEDIUM,
    SOUND_CHANNEL_CITY_HOUSE_GOOD,
    SOUND_CHANNEL_CITY_HOUSE_POSH,
    SOUND_CHANNEL_CITY_AMPHITHEATER,
    SOUND_CHANNEL_CITY_THEATER,
    SOUND_CHANNEL_CITY_HIPPODROME,
    SOUND_CHANNEL_CITY_COLOSSEUM,
    SOUND_CHANNEL_CITY_GLADIATOR_SCHOOL,
    SOUND_CHANNEL_CITY_LION_PIT,
    SOUND_CHANNEL_CITY_ACTOR_COLONY,
    SOUND_CHANNEL_CITY_CHARIOT_MAKER,
    SOUND_CHANNEL_CITY_GARDEN,
    SOUND_CHANNEL_CITY_CLINIC,
    SOUND_CHANNEL_CITY_HOSPITAL,
    SOUND_CHANNEL_CITY_BATHHOUSE,
    SOUND_CHANNEL_CITY_BARBER,
    SOUND_CHANNEL_CITY_SCHOOL,
    SOUND_CHANNEL_CITY_ACADEMY,
    SOUND_CHANNEL_CITY_LIBRARY,
    SOUND_CHANNEL_CITY_PREFECTURE,
    SOUND_CHANNEL_CITY_FORT,
    SOUND_CHANNEL_CITY_TOWER,
    SOUND_CHANNEL_CITY_TEMPLE_CERES,
    SOUND_CHANNEL_CITY_TEMPLE_NEPTUNE,
    SOUND_CHANNEL_CITY_TEMPLE_MERCURY,
    SOUND_CHANNEL_CITY_TEMPLE_MARS,
    SOUND_CHANNEL_CITY_TEMPLE_VENUS,
    SOUND_CHANNEL_CITY_MARKET,
    SOUND_CHANNEL_CITY_GRANARY,
    SOUND_CHANNEL_CITY_WAREHOUSE,
    SOUND_CHANNEL_CITY_SHIPYARD,
    SOUND_CHANNEL_CITY_DOCK,
    SOUND_CHANNEL_CITY_WHARF,
    SOUND_CHANNEL_CITY_PALACE,
    SOUND_CHANNEL_CITY_ENGINEERS_POST,
    SOUND_CHANNEL_CITY_SENATE,
    SOUND_CHANNEL_CITY_FORUM,
    SOUND_CHANNEL_CITY_RESERVOIR,
    SOUND_CHANNEL_CITY_FOUNTAIN,
    SOUND_CHANNEL_CITY_WELL,
    SOUND_CHANNEL_CITY_MILITARY_ACADEMY,
    SOUND_CHANNEL_CITY_ORACLE,
    SOUND_CHANNEL_CITY_BURNING_RUIN,
    SOUND_CHANNEL_CITY_WHEAT_FARM,
    SOUND_CHANNEL_CITY_VEGETABLE_FARM,
    SOUND_CHANNEL_CITY_FRUIT_FARM,
    SOUND_CHANNEL_CITY_OLIVE_FARM,
    SOUND_CHANNEL_CITY_VINE_FARM,
    SOUND_CHANNEL_CITY_PIG_FARM,
    SOUND_CHANNEL_CITY_QUARRY,
    SOUND_CHANNEL_CITY_IRON_MINE,
    SOUND_CHANNEL_CITY_TIMBER_YARD,
    SOUND_CHANNEL_CITY_CLAY_PIT,
    SOUND_CHANNEL_CITY_WINE_WORKSHOP,
    SOUND_CHANNEL_CITY_OIL_WORKSHOP,
    SOUND_CHANNEL_CITY_WEAPONS_WORKSHOP,
    SOUND_CHANNEL_CITY_FURNITURE_WORKSHOP,
    SOUND_CHANNEL_CITY_POTTERY_WORKSHOP,
    SOUND_CHANNEL_CITY_EMPTY_LAND,
    SOUND_CHANNEL_CITY_RIVER,
    SOUND_CHANNEL_CITY_MISSION_POST,
};

void sound_city_init();

void sound_city_set_volume(int percentage);

void sound_city_mark_building_view(building* b, int direction);

void sound_city_decay_views();

void sound_city_play();