#pragma once

#include "core/time.h"
#include "sound/channel.h"

#include <array>

class building;

enum e_sound_dir { 
    SOUND_DIRECTION_LEFT = 0,
    SOUND_DIRECTION_CENTER = 2,
    SOUND_DIRECTION_RIGHT = 4
};

enum e_sound_channel_city {
    SOUND_CHANNEL_CITY_NONE = 0,
    SOUND_CHANNEL_CITY_START = SOUND_CHANNEL_CITY_MIN,
    SOUND_CHANNEL_CITY_HOUSE_SLUM = SOUND_CHANNEL_CITY_MIN,
    SOUND_CHANNEL_CITY_HOUSE_POOR,
    SOUND_CHANNEL_CITY_HOUSE_MEDIUM,
    SOUND_CHANNEL_CITY_HOUSE_GOOD,
    SOUND_CHANNEL_CITY_HOUSE_POSH,
    SOUND_CHANNEL_CITY_BOOTH,
    SOUND_CHANNEL_CITY_BANDSTAND,
    SOUND_CHANNEL_CITY_PAVILION,
    SOUND_CHANNEL_CITY_SENET_HOUSE,
    SOUND_CHANNEL_CITY_JUGGLER_SCHOOL,
    SOUND_CHANNEL_CITY_DANCE_SCHOOL,
    SOUND_CHANNEL_CITY_CONSERVATORY,
    SOUND_CHANNEL_CITY_GARDEN,
    SOUND_CHANNEL_CITY_APOTHECARY,
    SOUND_CHANNEL_CITY_PHYSICIAN,
    SOUND_CHANNEL_CITY_MORTUARY,
    SOUND_CHANNEL_CITY_DENTIST,
    SOUND_CHANNEL_CITY_FIREMAN,
    SOUND_CHANNEL_CITY_TOWER,
    SOUND_CHANNEL_CITY_TEMPLE_OSIRIS,
    SOUND_CHANNEL_CITY_TEMPLE_RA,
    SOUND_CHANNEL_CITY_TEMPLE_PTAH,
    SOUND_CHANNEL_CITY_TEMPLE_SETH,
    SOUND_CHANNEL_CITY_TEMPLE_BAST,
    SOUND_CHANNEL_CITY_SHRINE_OSIRIS,
    SOUND_CHANNEL_CITY_SHRINE_RA,
    SOUND_CHANNEL_CITY_SHRINE_PTAH,
    SOUND_CHANNEL_CITY_SHRINE_SETH,
    SOUND_CHANNEL_CITY_SHRINE_BAST,
    SOUND_CHANNEL_CITY_MARKET,
    SOUND_CHANNEL_CITY_GRANARY,
    SOUND_CHANNEL_CITY_STORAGE_YARD,
    SOUND_CHANNEL_CITY_SHIPYARD,
    SOUND_CHANNEL_CITY_DOCK,
    SOUND_CHANNEL_CITY_WHARF,
    SOUND_CHANNEL_CITY_PALACE,
    SOUND_CHANNEL_CITY_ENGINEERS_POST,
    SOUND_CHANNEL_CITY_FORUM,
    SOUND_CHANNEL_CITY_WATER_SUPPLY,
    SOUND_CHANNEL_CITY_WELL,
    SOUND_CHANNEL_CITY_BURNING_RUIN,
    SOUND_CHANNEL_CITY_GRAIN_FARM,
    SOUND_CHANNEL_CITY_FIG_FARM,
    SOUND_CHANNEL_CITY_QUARRY,
    SOUND_CHANNEL_CITY_GOLD_MINE,
    SOUND_CHANNEL_CITY_TIMBER_YARD,
    SOUND_CHANNEL_CITY_CLAY_PIT,
    SOUND_CHANNEL_CITY_WEAPONS_WORKSHOP,
    SOUND_CHANNEL_CITY_POTTERY_WORKSHOP,
    SOUND_CHANNEL_CITY_EMPTY_LAND,
    SOUND_CHANNEL_CITY_RIVER,
    SOUND_CHANNEL_CITY_HUNTER_LOUDGE,
    SOUND_CHANNEL_CITY_POLICE,
    SOUND_CHANNEL_CITY_ROCK,
    SOUND_CHANNEL_CITY_STATUE,
    SOUND_CHANNEL_CITY_TAX_COLLECTOR,
    SOUND_CHANNEL_CITY_MANSION,
    SOUND_CHANNEL_CITY_TREE,
    SOUND_CHANNEL_CITY_WATER,
    SOUND_CHANNEL_CITY_SHRUB,
    SOUND_CHANNEL_CITY_CANAL,
    SOUND_CHANNEL_CITY_MEADOW,
    SOUND_CHANNEL_CITY_FLOODPLAIN,
    SOUND_CHANNEL_CITY_MARSHLAND,
    SOUND_CHANNEL_CITY_CHICKFARM,
    SOUND_CHANNEL_CITY_COWFARM,
};

struct city_sound_channel {
    int in_use;
    int available;
    int total_views;
    int views_threshold;
    int direction_views[5];
    int channel;
    int times_played;
    time_millis last_played_time;
    time_millis delay_millis;
    int should_play;
};

struct city_sounds_t {
    time_millis last_update_time;
    std::array<city_sound_channel, 96> channels;
};

void sound_city_init();
const city_sounds_t &sound_city_channels();
void sound_city_mark_building_view(building* b, int direction);
void sound_city_mark_terrain_view(int terrain, int grid_offset, int direction);
void sound_city_decay_views();
void sound_city_play();