/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.0.1-20-g2df8aaa8c5-20240716"
#endif /* AVUTIL_FFVERSION_H */
