#ifndef WINDOW_POPUP_DIALOG_H
#define WINDOW_POPUP_DIALOG_H

enum e_popup_dialog_opt {
    POPUP_DIALOG_NONE = -1,
    POPUP_DIALOG_QUIT = 0,
    POPUP_DIALOG_OPEN_TRADE = 2,
    POPUP_DIALOG_SEND_GOODS = 4,
    POPUP_DIALOG_DISPATCH_GOODS = 6,
    POPUP_DIALOG_NOT_ENOUGH_GOODS = 8,
    POPUP_DIALOG_NO_LEGIONS_AVAILABLE = 10,
    POPUP_DIALOG_NO_LEGIONS_SELECTED = 12,
    POPUP_DIALOG_SEND_TROOPS = 14,
    POPUP_DIALOG_DELETE_FORT = 16,
    POPUP_DIALOG_MISSING_CD = 18,
    POPUP_DIALOG_DELETE_BRIDGE = 20,
    POPUP_DIALOG_QUIT_WITHOUT_SAVING = 22,
    POPUP_DIALOG_OLD_VERSION = 24,
    //
    POPUP_DIALOG_EDITOR_BURIAL_PROVISIONS_TOO_MANY = 26,
    POPUP_DIALOG_EDITOR_BURIAL_PROVISIONS_NOT_AVAILABLE = 28,
    POPUP_DIALOG_BURIAL_PROVISIONS_NOT_ENOUGH_GOODS = 30,
    POPUP_DIALOG_BURIAL_PROVISIONS_ALL_DONE = 32,
    //
    POPUP_DIALOG_EDITOR_CITIES_TOO_MANY = 34,
    POPUP_DIALOG_TRANSPORT_SHIP_NEEDED = 36,
    POPUP_DIALOG_LAND_TROOPS_NEEDED = 38,
    POPUP_DIALOG_NO_TROOPS_NEEDED = 40,
    POPUP_DIALOG_TROOPS_AWAY = 42,
    POPUP_DIALOG_WARSHIP_AWAY = 44,
    //
    POPUP_DIALOG_GOOD_PRICE_CANNOT_CHANGE = 46,
    POPUP_DIALOG_ERROR_NEEDS_LINEN = 48,
    POPUP_DIALOG_ERROR_NEEDS_BEER = 50,
    POPUP_DIALOG_ERROR_NEEDS_PAPYRUS = 52,
    POPUP_DIALOG_MORTUARIES_NEEDS_LINEN = 54,
    POPUP_DIALOG_SENETS_NEEDS_BEER = 56,
    POPUP_DIALOG_SCHOOLS_NEEDS_PAPYRUS = 58,
    POPUP_DIALOG_LIBRARIES_NEEDS_PAPYRUS = 60,
    POPUP_DIALOG_ERROR_NEEDS_COPPER = 62,
    POPUP_DIALOG_WEAPONSMITHS_NEEDS_COPPER = 64,
    POPUP_DIALOG_ERROR_NEEDS_WOOD = 66,
    POPUP_DIALOG_CHARIOTMAKERS_NEEDS_WOOD = 68,
    POPUP_DIALOG_ERROR_NEEDS_RECRUITER = 70,
    POPUP_DIALOG_INFANTRY_NEEDS_RECRUITER = 72,
    POPUP_DIALOG_ARCHERS_NEEDS_RECRUITER = 74,
    POPUP_DIALOG_CHARIOTEERS_NEEDS_RECRUITER = 76,
    POPUP_DIALOG_ACADEMIES_NEEDS_RECRUITER = 78,
    POPUP_DIALOG_ERROR_NEEDS_WEAPONS = 80,
    POPUP_DIALOG_ERROR_NEEDS_CHARIOTS = 82,
    POPUP_DIALOG_INFANTRY_NEEDS_WEAPONS = 84,
    POPUP_DIALOG_CHARIOTEERS_NEEDS_CHARIOTS = 86,
    //
    POPUP_DIALOG_NO_FESTIVAL_SQUARE = 88,
    //
    POPUP_DIALOG_DELETE_DYNASTY = 90,
    POPUP_DIALOG_DYNASTY_NAME_EXISTS = 92,
    POPUP_DIALOG_NO_DYNASTY = 94,
    //
    POPUP_DIALOG_FESTIVAL_NOT_ENOUGH_MONEY = 96,
    POPUP_DIALOG_NO_WARSHIPS_AVAILABLE = 98,
    POPUP_DIALOG_NO_WARSHIPS_SELECTED = 100,
    POPUP_DIALOG_MULTIPLE_TROOP_DESTINATIONS = 102,
    //
    POPUP_DIALOG_DELETE_MONUMENT = 104,
    POPUP_DIALOG_DELETE_TEMPLE_COMPLEX = 106,
    //
    POPUP_DIALOG_EDITOR_CANT_SAVE_PREY_POINTS_INVALID = 108,
    POPUP_DIALOG_OVERWRITE_FILE = 110,
    //
    POPUP_DIALOG_NO_SELLERS = 112,
    POPUP_DIALOG_NO_BUYERS = 114,
    POPUP_DIALOG_NO_OPEN_TRADE_ROUTES = 116,
    POPUP_DIALOG_CANT_OPEN_TRADE_ROUTE_NOT_ENOUGH_MONEY = 119,
    //
    POPUP_DIALOG_EDITOR_CANT_SAVE_TOO_MANY_FOOD_TYPES = 121,
    POPUP_DIALOG_EDITOR_CANT_EDIT_MAP_LOW_RESOLUTION = 123,
    POPUP_DIALOG_EDITOR_CANT_CLOSE_MAP_TOO_MANY_FOOD_TYPES = 125,
    POPUP_DIALOG_EDITOR_CANT_SAVE_FISH_POINTS_INVALID = 127,
    POPUP_DIALOG_EDITOR_CANT_SAVE_LAND_ENTRY_POINTS_INVALID = 129,
    POPUP_DIALOG_EDITOR_CANT_SAVE_RIVER_ENTRY_POINTS_INVALID = 131,
    POPUP_DIALOG_EDITOR_CANT_SAVE_LAND_INVASION_POINTS_INVALID = 133,
    POPUP_DIALOG_EDITOR_CANT_SAVE_RIVER_INVASION_POINTS_INVALID = 135,
    //
    POPUP_DIALOG_PLEASE_INSERT_CD = 137,
    POPUP_DIALOG_ZOO_NEEDS_STRAW = 139,
    POPUP_DIALOG_NO_MISSIONS_WON_BY_FAMILY = 141,
};

enum e_popup_dialog_btns { e_popup_btns_ok = 0, e_popup_btns_yes = 1, e_popup_btns_yesno = 2 };

void window_popup_dialog_show(int type, void (*close_func)(bool accepted), e_popup_dialog_btns has_ok_cancel_buttons);

void window_popup_dialog_show_confirmation(int text_group, int text_id, void (*close_func)(bool accepted));

#endif // WINDOW_POPUP_DIALOG_H
