// DO NOT EDIT. This file is generated by CMake.
// Run CMake configure step to update it.
#include "game/system.h"

#define JULIUS_VERSION "0.0.2"
#define JULIUS_VERSION_SUFFIX "-20220921-e59343518-dirty"

const char *system_version(void)
{
    return JULIUS_VERSION JULIUS_VERSION_SUFFIX;
}
